### ISSUE TITLE
Test network node startup failure

### ISSUE THREAD

**Issue by wenre** [MystenLabs/sui#10263]
vmware ubuntu 22.04
ip:192.168.5.xxx
testnet

Follow the documentation below：
https://docs.sui.io/learn/exchange-integration-guide#install-a-sui-full-node-from-source

There is such a problem：
![image](https://user-images.githubusercontent.com/13760469/229265565-3bc0245b-f6f0-48c8-ac05-1bc7a1c792d0.png)

**Comment by staking4all** [comment]
Hi

I had the same problem

Just add seeds in p2p section in /opt/sui/config/validator.yaml. Mine is validator.yaml due to running validator. Will probably need to add in equivalent of full node

 seed-peers:
   - address: "/dns/sui-rpc-pt.testnet-pride.com/udp/8084"
     peer-id: 0b10182585ae4a305721b1823ea5a9c3ce7d6ac4b4a8ce35fe96d9914c8fcb73
   - address: "/dns/sui-rpc-pt2.testnet-pride.com/udp/8084"
     peer-id: bf45f2bd2bbc4c2d53d10c05c96085d4ef18688af04649d6e65e1ebad1716804
   - address: "/dns/sui-rpc-testnet.bartestnet.com/udp/8084"
   - address: "/ip4/38.242.197.20/udp/8080"
   - address: "/ip4/178.18.250.62/udp/8080"
   - address: "/ip4/162.55.84.47/udp/8084"
   - address: "/dns/wave-3.testnet.n1stake.com/udp/8084"

Hope it helps

**Comment by stefan-mysten** [comment]
Thanks for reporting this @wenre and thanks for your help on how to fix this issue @staking4all. I will close this issue for now as it's been stale for a while, but feel free to create a new issue if you still encounter problems.
