### ISSUE TITLE
Sui Indexer API (Sui doc content issue or request)

### ISSUE THREAD

**Issue by sheldonkreger** [MystenLabs/sui#10468]
The Event API code was deleted in the latest testnet and devnet releases. It was replaced by some new code called the Sui Indexer API. The Indexer API has not been documented. Below is a link to the old documentation.

https://docs.sui.io/build/event_api

Although the two systems are similar, there are some key features which appear to be gone in the new Indexer API. Specifically:

- The old Event API allowed subscriptions to event types NewObject, DeleteObject, TransferObject, Publish package, Epoch changes, and Checkpoints. The new Indexer API only supports Event Filters for a single, ambiguous object type.
- There are some new features for querying historical events, which are great for backfilling.

My team had implemented code with the Rust SDK to subscribe to the old Event Types and index data in real-time. Our indexer powers four products at our company, all of which are now blocked. We need a reliable way to be notified of new objects, object mutations, and object deletions.

These are basic CRUD operations which need to be processed in our data pipelines so that our databases can stay in sync with Sui. The new Indexer API seems like the solution, but I don't see any way to filter the event streams in a similar way. Perhaps the new [EventFilter ](https://github.com/MystenLabs/sui/blob/aed2b469bd4bc6aed825e4791ab24034e51354fd/crates/sui-json-rpc-types/src/sui_event.rs#L112)and the MoveEventType field can be leveraged - but some clarity would be greatly appreciated.

We are eager to test and help document the Indexer API changes.

Thank you.

**Comment by gegaowp** [comment]
copying a thread about this on telegram

> Ge | Mysten:
> event types NewObject, DeleteObject, TransferObject
a while ago, we had an extended discussion and decided to remove these from "events", now they are in the "object_changes" of a tx response

> Sheldon Kreger:
I see. Thanks for letting me know.

> Sheldon Kreger:
Does this mean they are only in scope for the client when it issues the transaction?

> Sheldon Kreger:
Or is the TX response somehow emitted across the network?

> Ge | Mysten:
sure thing, meanwhile the "events" will only include "move events" that are explicitly generated by users' Move modules

> Ge | Mysten:
> TX response somehow emitted across the network
this is public info of the network, you can use getTransactionBlock to get them

> Ge | Mysten:
the getTransactionBlock has some options you can configure, 
pub struct SuiTransactionBlockResponseOptions {
    /// Whether to show transaction input data. Default to be False
    pub show_input: bool,
    /// Whether to show bcs-encoded transaction input data
    pub show_raw_input: bool,
    /// Whether to show transaction effects. Default to be False
    pub show_effects: bool,
    /// Whether to show transaction events. Default to be False
    pub show_events: bool,
    /// Whether to show object_changes. Default to be False
    pub show_object_changes: bool,
    /// Whether to show balance_changes. Default to be False
    pub show_balance_changes: bool,
}

> Ge | Mysten:
as you can see, there is one for object_changes

> Ge | Mysten:
the reasoning behind this was 1. all these object & system events can be derived from tx, so no need to store them per se; 2. all those object & other "system" events ended up taking a lot of storage on FN but no one is paying for the storage explicitly, which was getting a burden for the whole network

> Sheldon Kreger:
I see. It sounds like we need to make several rpc calls in order to track object changes. And we also have to manually iterate an rpc call to know when new checkpoints are synced. 
This introduces substantial latency to our data pipelines. We were indexing objects very quickly with the Event Stream API.

> Sheldon Kreger:
Thank you for explaining the reasoning. It sounds like you put a lot of thought into it.

> Ge | Mysten:
we had an extensive meeting a couple of months back with many key engs on that meeting indeed :)

> Ge | Mysten:
> make several rpc calls in order to track object changes
if you want to track all object changes, now you can do 
    #[method(name = "queryTransactionBlocks", blocking)]
    fn query_transaction_blocks(
        &self,
        /// the transaction query criteria.
        query: SuiTransactionBlockResponseQuery,
        /// An optional paging cursor. If provided, the query will start from the next item after the specified cursor. Default to start from the first item if not specified.
        cursor: Option<TransactionDigest>,
        /// Maximum item returned per page, default to QUERY_MAX_RESULT_LIMIT if not specified.
        limit: Option<usize>,
        /// query result ordering, default to false (ascending order), oldest record first.
        descending_order: Option<bool>,
    ) -> RpcResult<TransactionBlocksPage>;

> Sheldon Kreger:
Very interesting!

> Ge | Mysten:
this basically will give you pages of all tx, on each page of tx, you can read the object changes of each tx

> Ge | Mysten:
even better if you only care about certain addresses, you can only query them too

> Sheldon Kreger:
Using this interface sounds like a good plan.

> Ge | Mysten:
yeah, one nuanced thing we have fixed is that, the next_cursor is now exclusive, so even if you have caught up with the latest page, you can just keep iterating using the returned nextCursor, it will not double count anything, but will fetch new page whenever it's available

> Ge | Mysten:
this is not a stream per se, but should be used as a stream-like thing

> Sheldon Kreger:
Is it possible to leave the query running to receieve new txns? Or should we close the request, track the item ID
OH you knew my question already,

> Sheldon Kreger:
Thanks!

> Ge | Mysten:
I was there as well :)

> Ge | Mysten:
I had to explicitly handle that, which was tedious, so I fixed it!

> Sheldon Kreger:
We might be the first ones trying, but I suspect many teams will need to do this.

> Paul Fidika - The Sui Dude:
So instead of subscribing to an event stream we are polling the fullnode for all transactions constantly?

> Ge | Mysten:
if you want to wait a bit when you have caught up, there is a hasNextPage on the response, you can wait for 1 sec or sth

> Sheldon Kreger:
Last question from me....

> Sheldon Kreger:
Are these transactions guaranteed to come through every node at each checkpoint? Or onoy the nodes where the issuing client requested certificates?

> Ge | Mysten:
yeah please share with others if you saw them asking, I felt this very useful but might not be well-known yet

> Sheldon Kreger:
I am wondering if I can capture all transactions by polling just one data node.

> Ge | Mysten:
as you can see in the TransactionFilter, there is a Checkpoint one, I would recommend using that if you want to query all; when N checkpoint is done, you move to the next

> Ge | Mysten:
per you question, it should include all tx, both locally submitted ones and ones synced via checkpoints from other nodes

> Sheldon Kreger:
Excellent, that is great news.
