### ISSUE TITLE
Improve new user (developer) journey

### ISSUE THREAD

**Issue by bwann52** [MystenLabs/sui#1065]
Let's define and improve the ideal happy path for new developers visiting our dev portal.

Goals:
1) Complete Sui's version of hello world
2) We want developers to get enough info to understand and get excited

@bholc646 @kyleqian have already tried going thru some of our docs.
And @kyleqian suggested https://project-serum.github.io/anchor/tutorials/tutorial-0.html#clone-the-repo as a good example of a basic hello world.

@Clay-Mysten

**Comment by Clay-Mysten** [comment]
Thanks, Bauer! You mentioned Kyle had pain points. Kyle, can you add them here?

**Comment by kyleqian** [comment]
Here are my notes (goes without saying that some of these could just be my preference 😁):
* I'm someone who learns best by example, and I was unable to find a comfortable starting point at first
* The tictactoe tutorial is a bit advanced as the first exposure. I think it _could_ work, similar to [Solana's escrow example](https://paulx.dev/blog/2021/01/14/programming-on-solana-an-introduction/), but it would need much more elaboration on what's happening, rather than just stepping through the "how".
* The code samples in the repo were useful, but I still didn't feel comfortable using them until I better understood the basics of the programming model
* I didn't realize that what I was looking for was somewhere inside https://docs.sui.io/build/move. On first glance, I thought that page was going to be more theoretical, so I skipped over it. The most useful part for me was the "Writing a package" section. Shortly after going through it and doing my own tinkering, a bunch of concepts clicked into place.

Suggestions:
* Have a hello world example come very early in onboarding. I like the one Solana has here: https://github.com/solana-labs/example-helloworld.
  * I think it's important that this example actually gives you a functional project that does something and which you can start editing on your own to produce different effects.
  * The basic example we currently have is hidden in a page and has no logic.
* Create a series of these examples, each demonstrating a new topic.
  * Each example should be its own project, each able to be cloned / edited / redeployed.
  * This is what Anchor does well: https://project-serum.github.io/anchor/tutorials/tutorial-1.html#clone-the-repo. Notice how there are different tutorials to demonstrate the early concepts devs must learn. For each tutorial, users are asked to clone an example repo, then are taught basic concepts demonstrated by the example, which the dev can deploy + run + verify on their own.
* Walkthroughs for more complex examples like tictactoe could perhaps have their own section, or be later in a tutorial series

**Comment by Clay-Mysten** [comment]
This is excellent, concrete input Kyle. I appreciate it immensely and will review it and the tutorials you recommend above in preparation for our meeting tomorrow. Thanks so much!

**Comment by Clay-Mysten** [comment]
I'm noting we are on the path to:
Identify the audiences/users
Outline respective workflows of users
Draft instructions for enabling most common workflows
Test instructions internally
Conduct user testing and case studies

Xun has made excellent progress here:
https://github.com/MystenLabs/sui/blob/main/doc/src/build/programming-with-objects/index.md

With notes on that content in:
https://app.golinks.io/programming-objects-series-notes

We are tracking details in:
Sui Critical User Journeys Task List
https://app.golinks.io/sui-cuj-doc

Which is resulting in a restructure of both the Learn and Build sections, to be tracked in separate issues I will reference here.

**Comment by Clay-Mysten** [comment]
Adding Sam to review these PRs per Adam before I merge:
https://github.com/MystenLabs/sui/issues/1362
https://github.com/MystenLabs/sui/issues/1363

**Comment by Clay-Mysten** [comment]
+Godwin

Hi all,

Just catching you up on progress. We are soon to embark upon:
https://github.com/MystenLabs/sui/issues/1363
https://github.com/MystenLabs/sui/issues/1362

In preparation for the likely breakage that will ensure - despite my best efforts, `grep`, etc. - I am installing other external link checkers and fixing up issues encountered when running them. We need a clean baseline before shifting things about.

To this end, I've reviewed and starting fixing issues reported in Francois' excellent CI link checker:
https://github.com/MystenLabs/sui/pull/1766
https://github.com/tcort/markdown-link-check/issues/91

And documented our various tools for link checking in a new section near the bottom of:
https://app.golinks.io/dev-portal-work

Note the TODOs to better route these issues to the Docs team. Much, much more to come.

**Comment by Clay-Mysten** [comment]
I should note an outstanding concern is catching broken named anchors, ex. page-name#new-anchor. I haven't found a reliable solution for those yet.

Also, Godwin please do let me know how and where to add redirects. Thanks!

**Comment by Clay-Mysten** [comment]
Godwin, here is that text file output from `linkchecker` showing the broken image:
[404s-in-live-site.txt](https://github.com/MystenLabs/sui/files/8681380/404s-in-live-site.txt)

```
Start checking at 2022-05-11 14:16:31-007

URL        `/img/Sui-logo-blue.png'
Parent URL https://docs.sui.io/_nuxt/css/9baafdd.css, line 4, col 70228
Real URL   https://docs.sui.io/img/Sui-logo-blue.png
Check time 2.864 seconds
Size       1KB
```

**Comment by Clay-Mysten** [comment]
See more progress in:
https://github.com/MystenLabs/sui/issues/1362
https://github.com/MystenLabs/sui/issues/1363

**Comment by Clay-Mysten** [comment]
And @joyqvq too!

**Comment by Clay-Mysten** [comment]
More external contributions, found on Discord in the #content channel:
https://medium.com/@megalodonear/sui-installing-node-step-by-step-guide-for-beginners-5c766ce94ab9

See also the already outdated:
https://cryptech-nodes.medium.com/sui-installation-bff21222bcad

And from our very own Lu:
https://app.golinks.io/local-net-flow

The latter two already noted in:
https://github.com/MystenLabs/sui/issues/1362

We are starting to evaluate a full-blown contributors program in:
https://github.com/MystenLabs/sui/issues/3380

**Comment by Clay-Mysten** [comment]
Release note request tracked in:
https://github.com/MystenLabs/sui/issues/3313

**Comment by Clay-Mysten** [comment]
Another external doc with potential:
https://mirror.xyz/0xf3bF9DDbA413825E5DdF92D15b09C2AbD8d190dd/WfE7EVJ3xtG0gPPbB8xG_3lswshWfJH-Pgps9CsA7UU

**Comment by Clay-Mysten** [comment]
Adding this user-generated doc from @huitseeker as a solid contribution.

Will likely peel off the Community endeavor in a distinct sub-issue.

**Comment by Clay-Mysten** [comment]
I believe we have accomplished all we set out to do here. Work continues in the Build docs refactor issue:
https://github.com/MystenLabs/sui/issues/1362

And the new Contributors issue:
https://github.com/MystenLabs/sui/issues/3901
