### ISSUE TITLE
Sui Explorer  doesn't support wallet standard

### ISSUE THREAD

**Issue by sunny0529** [MystenLabs/sui#11447]
## Steps to Reproduce Issue
1. Open any DAPP using the current Wallet Standard.
2. Try to select an account on a specific chain and network to execute a specific function.
3. Note that there is no option available to select an account on a specific chain and network.

e.g.
1. Call function <function call>.
2. Use return value and call <other function call>.

## Expected Result

Specify what outcome you expected should have resulted, but didn't.

e.g.
Expected <other function call> to return 42.

## Actual Result

Specify what the actual unexpected outcome was.

e.g.
<other function call> returned 41.

## System Information

* OS: <specify OS version>
* Compiler: <specify compiler version>

**Comment by Jordan-Mysten** [comment]
We recently added support for selecting between accounts in the UI. Selecting between chains in the explorer doesn't make a lot of sense because the explorer is logically scoped to a specific chain, but it should trigger the signing / execution against a given chain, which I don't think we do. The whole multi-chain piece of our Wallet Adapters is something that we really want to improve in general.
