### ISSUE TITLE
Event API documentation is inconsistent with auto-generated JSON-RPC documentation

### ISSUE THREAD

**Issue by mlegner** [MystenLabs/sui#11988]
It seems that parts of the [event-API documentation](https://docs.sui.io/build/event_api) is out of sync with the current implementation and the [autogenerated JSON-RPC documentation](https://docs.sui.io/sui-jsonrpc) (probably since #9838):
- The examples use `sui_getEvents` but should probably use `suix_queryEvents`.
- Some of the filters/query parameters don't seem to exist (any more); example reply: '"unknown variant `EventType`, expected one of `Sender`, `Transaction`, `Package`, `MoveModule`, `MoveEventType`, `MoveEventField`, `TimeRange`, `All`, `Any`, `And`, `Or` at line 1 column 12"'
- The last parameter for the sorting order expects a boolean instead of a string like `Ascending`.
- The link https://docs.sui.io/build/pubsub#event-filters at https://docs.sui.io/sui-jsonrpc#suix_subscribeEvent is broken (should probably be https://docs.sui.io/build/event_api#event-filters).

**Comment by SuiSunbeam** [comment]
sui_getEvents and the mentioned link don't seem to be present in the document anymore.

EventType is still mentioned.

Can't see the mentioned sorting param doing a quick find in page.

The mentioned link doesn't seem to be present anymore (this document has been updated a few times since this issue was opened).
