### ISSUE TITLE
Explorer: view list of available functions in smart contract card

### ISSUE THREAD

**Issue by bwann52** [MystenLabs/sui#1205]
See list of functions in the smart contract

**Comment by todd-mystenlabs** [comment]
@bwann52, @awelc - we'll need to figure out how we ultimately want to display this. It's potentially wrapped up in how to show Move code in general in the explorer.

**Comment by awelc** [comment]
We already have this. We actually have more than this (potentially too much) - we also display bytecode representing the body of each function (@Andrew47 has been [working](https://github.com/MystenLabs/sui/issues/1043#issuecomment-1099442625) on pretty-printing this but I am not sure if this change has landed).

That being said, I think we only show this for internal modules (framework and std lib). We need the JSON encoding to show the object type as "package" in order to do this more generally. I tagged @patrickkuo on the relevant [issue](https://github.com/MystenLabs/sui/issues/1043#issuecomment-1098437094) and I think he is working on this already.
