### ISSUE TITLE
create TypeScript wrapper for signing service

### ISSUE THREAD

**Issue by stella3d** [MystenLabs/sui#1226]
A network service is being created for [custodial signing](https://github.com/MystenLabs/sui/issues/1223), and needs a friendly TypeScript / JS interface for web-native games and [node.js](https://nodejs.org/en/) / [deno](https://deno.land/) servers to use.

This should mirror [the C# wrapper ](https://github.com/MystenLabs/sui/issues/1225) as closely as possible while being idiomatic TypeScript

**Comment by todd-mystenlabs** [comment]
@666lcz - thought you'd be interested since you're (going to be) doing some TS API work.

**Comment by stella3d** [comment]
@todd-mystenlabs i assigned to myself by default, but happy to have @666lcz do implementation if we want. As long as we keep the language wrappers in sync

**Comment by todd-mystenlabs** [comment]
I leave that up to you two.  I just wanted @666lcz in the loop either way.  Thanks, @stella3d!

**Comment by todd-mystenlabs** [comment]
@stella3d / @666lcz - where did we land on this? I think it's a dependency for a DevNet P2 task.

**Comment by 666lcz** [comment]
@todd-mystenlabs IIUC this task is about creating a Typescript wrapper for the custodial signing service(which is not in the [DevNet Milestone](https://github.com/orgs/MystenLabs/projects/14/views/1?visibleFields=%5B3081862%2C%22Title%22%2C%22Assignees%22%2C%22Status%22%5D&sortedBy%5Bdirection%5D=asc&sortedBy%5BcolumnId%5D=3081862)). This issue is not part of the general [Typescript SDK](https://github.com/MystenLabs/sui/issues/1389) which has a broader audience which most likely don't need to use a custodial signing service

**Comment by stella3d** [comment]
yeah, actually we don't need this as much as we need the primary signer.  in fact, we don't need an sdk for this right now

**Comment by todd-mystenlabs** [comment]
Got it, ok!

Sent via Superhuman iOS ***@***.***>
