### ISSUE TITLE
Make Dev Portal support emojicode

### ISSUE THREAD

**Issue by bwann52** [MystenLabs/sui#1241]

**Comment by Clay-Mysten** [comment]
Thanks to Godwin for getting EMOJICODE supported in our Dev Portal:
https://gist.github.com/rxaviers/7360908

Now we should determine whether to use it or the standard callouts function of GitHub Markdown syntax for that warning and other notes in the doc:
https://github.com/github/docs/blob/main/contributing/content-style-guide.md#formatting-callouts
https://github.com/github/docs/blob/main/contributing/content-markup-reference.md#callout-tags

**Comment by Clay-Mysten** [comment]
We will use the simple prefix:
>

Testing now in:
https://github.com/MystenLabs/sui/pull/1265

**Comment by Clay-Mysten** [comment]
Documented internally as such:

Format callouts (notes, warnings, cautions, etc.) like so:
> **Note:** Some text

**Comment by Clay-Mysten** [comment]
And Xun...

**Comment by Jibz1** [comment]
@Clay-Mysten  I will look into it later this week.

**Comment by Clay-Mysten** [comment]
We don't have to do this, my friend. I was simply looking for a decision so I know how to proceed. We have some folks using it and others not. Trying to standardize...

**Comment by bwann52** [comment]
Can we provide a list of top 20 most useful emojis @lxfind @Clay-Mysten and @Jibz1 can implement. Then we can consider this issue closed.

**Comment by Clay-Mysten** [comment]
I'm adding Xun for guidance. I see :bulb: used here:
https://docs.sui.io/build/programming-with-objects/ch1-object-basics#create-sui-object

I would like to see:
❗ :exclamation:
❓ :question:
💬 :speech_balloon: (since they don't have :note: but rather :notes:)
🚫 :no_entry_sign:
⚠️ :warning: (already supported)

Xun, what other primary items from this list would you like to see be supported:
https://gist.github.com/rxaviers/7360908

**Comment by Jibz1** [comment]
@Clay-Mysten Full emoji support added. preview on the[ dev site](https://devportal-dev.web.app/build/programming-with-objects/ch1-object-basics) . I Will merge these changes with the staging and production site tonight.
