### ISSUE TITLE
Consolidate genesis logic and share among different node types

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#1297]
We start authorities with genesis.
However we currently don't start gateway with genesis. Instead, we attempt to sync after starting a gateway to download the genesis.
This has a few issues:
1. We are unable to download the genesis packages because they are not owned by any account.
2. If there are many genesis objects, we may fail to sync.
3. Once we have a full node, we will face similar problem: full node will not be able to obtain the genesis objects, because they don't come from transactions.
We should just start the gateway/fullnode with the same genesis config so that the gateway can start with the same genesis.

**Comment by patrickkuo** [comment]
current genesis is not deterministic, it generate random keys and objects, so it will create different result if we run it again in gateway even with the same genesis config.
We can create the client_db as part of the genesis process, so the gateway will have a "primed" db instead of an empty one when it first start.

But how do we handle this in production? A new joiner gateway will need to somehow obtain the genesis database? Maybe we need an api to download packages and objects from the Validators?

**Comment by lxfind** [comment]
Shouldn't we make the genesis config deterministic then?

**Comment by mystenmark** [comment]
I solved this in devnet by checking in a genesis config: https://github.com/MystenLabs/devnet/blob/mlogan/devnet/docker/validator/genesis.conf

This is not a long term solution

**Comment by bmwill** [comment]
Long term solution is to create a genesis blob/transaction which comprises the entirety of the initial state needed. I realized this a day or so ago and began working on fleshing this out since we'll need this for fullnodes

**Comment by mystenmark** [comment]
I'm not sure what is still required to close this bug? It seems like @bmwill has things in a state where we can have external node operators relatively easily.

**Comment by lxfind** [comment]
Close to merge with [#1837](https://github.com/MystenLabs/sui/issues/1837)
