### ISSUE TITLE
[Sui Wallet] Sign and verify signed message failed

### ISSUE THREAD

**Issue by vunguyen9404** [MystenLabs/sui#13215]
## Steps to Reproduce Issue
Hi,
I have tried to sign a message and verify a signed message. The sign message works fine, but the verify function returns an error.

e.g.
1. Call function `wallet.signMessage` from wallet-kit.
2. Use return value and call `verifySignedMessage` from SUI SDK `@mysten/sui.js`.

## Result

The result returns verify `false` with the signature just signed,
with other wallets like Martian, Glass, Suiet still working fine.

This error started a few days ago.

## System Information

* SDK: @mysten/sui.js v0.37.1

**Comment by jh-9527** [comment]
I have encountered the same problem. Have you found a solution?

**Comment by Jordan-Mysten** [comment]
There's a changes happening to message signing and verification that change the format of the signed messages to align with the Rust SDK. The Sui Wallet is already supporting the new format, which is why you see verification fail with the current released SDK. An updated SDK version should be released next week, or you can use the `@experimental` version of them, which has these changes.

**Comment by devflowx** [comment]
Change to version @mysten/sui.js v0.39.0 is working with wallet-kit. But  when upgrade to version 0.40.0 it happend again when use verifySignedMessage it's always return `false`

**Comment by Jordan-Mysten** [comment]
Latest wallet release and latest SDK releases resolve this.

**Comment by taofeek-ob** [comment]
Same issue persists when verifying signed message using sui or martian wallet, even on the demo app made by suiet: https://kit.suiet.app/docs/QuickStart

Somehow, no issue using ethos wallet. All wallet extensions are updated
