### ISSUE TITLE
[RPC] Official RPC speed optimization

### ISSUE THREAD

**Issue by uvd** [MystenLabs/sui#13392]
https://explorer-rpc.mainnet.sui.io/
https://fullnode.mainnet.sui.io/
https://rpc.mainnet.sui.io/

1. http2.0 is supported, currently only http1.1 is supported, with a limit on the number of concurrent requests 
2. If it is a cross-domain option request, the proxy returns directly to avoid a longer waiting time 
<img width="1345" alt="image" src="https://github.com/MystenLabs/sui/assets/10650592/e21de8f3-19a8-45c5-ad26-1d8aebc11725">

3. If possible, deploy multiple regions based on regional load balancing. Currently, only the United States is deployed. Other regions are slow 
4. Open an RPC that supports http3.0

**Comment by johnjmartin** [comment]
Hey @uvd, thanks for the issue.

The public fullnode endpoint (https://fullnode.mainnet.sui.io/ & https://rpc.mainnet.sui.io/)  isn't really designed for speed. It is intentionally rate-limited in order to prevent a "noisy-neighbor" situation, where a single client is abusing the endpoint and breaking access for others. The explorer-rpc endpoint is not meant to be used by the public, as it primarily serves [suiexplorer](https://suiexplorer.com/).

We do plan on implementing `3. deploy multiple regions based on regional load balancing[...]` (for the public fullnodes only). I'll bring `1. http2.0 support[...]`  and `2. [...] cross-domain option request [...]` to the team and see how easy that would be to do at the proxy layer.
