### ISSUE TITLE
Google index SEO optimization bug

### ISSUE THREAD

**Issue by bwann52** [MystenLabs/sui#1372]

**Comment by Clay-Mysten** [comment]
This appears to be the issue:
https://sui.io/robots.txt
https://docs.sui.io/robots.txt

Which both have:
```
Allow: /*.html$
```

But the HTML file extension doesn't exist:
https://docs.sui.io/learn/how-sui-works.html
"That page can't be found"
It looks like nothing found at this location. Try to navigate the menu or go to the home page."

Instead per:
https://developers.google.com/search/docs/advanced/robots/create-robots-txt

We should simply specify:
```
Allow: /
```

**Comment by Clay-Mysten** [comment]
I supplied the fix. If you point me at the files, I will fix them directly.

**Comment by Jibz1** [comment]
@Clay-Mysten that file is auto generated. I already have a fix. should be live soon

**Comment by Jibz1** [comment]
@Clay-Mysten  the robots.txt is updated https://docs.sui.io/robots.txt

**Comment by Clay-Mysten** [comment]
Awesome, Godwin! Now we wait. :-)

**Comment by todd-mystenlabs** [comment]
How long will this take to see if it works?

**Comment by Jibz1** [comment]
I don't think this will make a difference.

**Comment by bwann52** [comment]
Update: we are seeing "Discovered - currently not indexed" issue across sui.io and docs.sui.io; unclear on if we have this issue for mystenlabs.com @pchrysochoidis can you verify?

**Comment by Clay-Mysten** [comment]
Where are you seeing those messages? As for this change not making a
difference, I would differ. We were previously excluding you are previously
excluding sll of our Web pages.

 Do we link to our sites from the various blog posts we sent out?

**Comment by Clay-Mysten** [comment]
Hmm, I'm now wondering if our use of the .io top-level domain (or domain extension) on docs.sui.io and sui.io, rather than .com, is affecting our search engine optimization. My digging is inconclusive. But I will note these findings:

Google claims to handle all top-level domains the same:
https://developers.google.com/search/blog/2015/07/googles-handling-of-new-top-level

But then links from there to this list of top-level domains (extensions):
https://en.wikipedia.org/wiki/Generic_top-level_domain

But that list doesn't show .io explicitly. Instead, that page states, "By default, most ccTLDs (with exceptions)  result in Google using these to geotarget the website; it tells us that the website is probably more relevant in the appropriate country."

And that reference links to this list:
https://en.wikipedia.org/wiki/Country_code_top-level_domain

Which shows .io as both the country code for the British Indian Ocean Territory and as the "domain hack" for input output (naturally).

The page states, "Generic Country Code Top-Level Domain or gccTLD refers to those TLDs which are technically "non-restricted ccTLDs" but used like traditional generic TLDs (gTLDs) rather than "country" targeted ones.[86][87][88] Most of the gccTLDs are primarily used as domain hacks."

Like I said, inconclusive. I think we simply need more external links into the sites. See my question on those blog posts. Did those link into GitHub or *.sui.io?

**Comment by Clay-Mysten** [comment]
Alright, I did a quick audit and see links to our sites from these blog posts, at the very bottom:
https://medium.com/mysten-labs/sui-developer-kit-building-optimized-ux-488ec3f3f1d2
https://medium.com/mysten-labs/announcing-sui-1f339fa0af08

But not:
https://medium.com/mysten-labs/sui-dynamic-nfts-to-enhance-gameplay-47ee79bbb89c (sui.io and GitHub but not docs.sui.io) 
https://medium.com/mysten-labs/suiecho-bootstrapping-sui-communities-d3a59606dfcb
https://medium.com/mysten-labs/women-of-mysten-labs-5cc45c2872e6
https://medium.com/mysten-labs/introducing-mysten-labs-building-foundational-infra-for-web3-7e5ec3df1ccb

Some of this makes sense since the lower, older posts date prior to the existence of our sui.io and docs.sui.io sites (not sure when mystenlabs.com launched). But the newer ones don't link to docs.sui.io prominently whatsoever. And this is especially concerning since most (all?) of the news articles on our launch go to Medium, for example:
https://www.technomati.com/blockchain/2022/03/23/sui-blockchain-launched-by-frail-diem-developers-for-web3-scalability/
https://en.ethereumworldnews.com/sui-blockchain-launched-by-former-diem-developers-for-web3-scalability/
https://cryptoharry.net/sui-blockchain-launched-by-former-diem-developers-for-web3-scalability/
https://onlinecurrency.in/sui-blockchain-launched-by-former-diem-builders-for-web3-scalability/

Koh and team, can we make updates to these posts? We could sure use more external links into our sites.

**Comment by Clay-Mysten** [comment]
Well, I think we nailed down the issue, namely that we haven't been linking prominently to our sites from our blog posts. Thankfully, Jennifer did so yesterday in the Narwhal and Tusk.

**Comment by Clay-Mysten** [comment]
https://medium.com/mysten-labs/announcing-narwhal-tusk-open-source-3721135abfc3

And sure enough, we hit more than 200 users or more in a day on docs. sui.io for the first time since our announcement week:
<img width="1532" alt="Screen Shot 2022-04-20 at 10 53 11 AM" src="https://user-images.githubusercontent.com/100217682/164301144-6f1f06aa-ac87-4e1f-bb4a-0a338c464fd9.png">

Meanwhile, Godwin points out our Learn Sui page has now been indexed by Google:
https://files.slack.com/files-pri/T02CJ2KHAKF-F03BTTRFRM5/screen_shot_2022-04-20_at_1.22.38_pm.png

And our site received numerous clicks from Google search yesterday.
https://files.slack.com/files-pri/T02CJ2KHAKF-F03CATVU99S/t.png

FWIW, I still think the robots.txt file was also biting us. Regardless, I consider this issue solved. Let's make these announcements repeatable next.

**Comment by Clay-Mysten** [comment]
Let's pick this up in:
Creating Announcing Features process #16
https://github.com/MystenLabs/Prose/issues/16

**Comment by Clay-Mysten** [comment]
Finally, I am noting GitHub traffic also spiked seemingly as a result of the N/T announcement:
<img width="1444" alt="Screen Shot 2022-04-20 at 3 40 07 PM" src="https://user-images.githubusercontent.com/100217682/164336743-3fa6f906-17b8-402c-ba85-9b30fcad79ea.png">

**Comment by Clay-Mysten** [comment]
More evidence we need generate more external (Medium, etc.) blog posts that link to our sites prominently:
https://www.google.com/search?q=%22docs.sui.io%22

Narwhal was our most popular page yesterday:
<img width="1444" alt="Screen Shot 2022-04-21 at 10 20 59 AM" src="https://user-images.githubusercontent.com/100217682/164516471-8e86cf4e-99a6-473f-b351-fe4e182793c4.png">

**Comment by Clay-Mysten** [comment]
The latest view of that GitHub traffic spike:
<img width="1444" alt="Screen Shot 2022-04-21 at 10 33 01 AM" src="https://user-images.githubusercontent.com/100217682/164518054-e5e55deb-4022-46fa-8fc6-47090c8a5e41.png">
