### ISSUE TITLE
Sui Install Failed 

### ISSUE THREAD

**Issue by pichtranst123** [MystenLabs/sui#13924]
##Error
I installed Sui in VirtualBoxWindow and nothing happens.
When I install the same package in main Window and got "failed to run custom build command for narhal-type v0.1.0"
That shit take my two-hours 
##Auth: pichtranst123

**Comment by stefan-mysten** [comment]
@pichtranst123 - could you tell us a bit more about the installation in VirtualBox? What OS are you running VirtualBox in? What OS is running inside your Virtual Box?
The best would be to copy paste the error. Also, when you say nothing happens, nothing happens when installing or after installing, when running a command?

**Comment by stefan-mysten** [comment]
@pichtranst123 did you manage to get it working?
