### ISSUE TITLE
Keep alive TCP connection with consensus

### ISSUE THREAD

**Issue by asonnino** [MystenLabs/sui#1452]
The current `ConsensusSubmitter` module re-creates a new connection every time a user needs to submit a transaction containing shared objects. The reason why it is implemented that way is because it is the simplest way to avoid taking `self` as a mutable reference (which is forbidden by the `AuthorityServer`).

**Comment by asonnino** [comment]
From @huitseeker 

The problem with this (https://github.com/MystenLabs/sui/issues/1452) is not so much that you're wasteful, it's that you're going to run against an fd limit pretty fast.
An immediate workaround is the tricks akin to https://github.com/MystenLabs/sui/commit/43e91906ade07a8a2f74955e45479d14af530171 but a better fix is just to have an ad-hoc connection pool using a library like [bb8](https://github.com/djc/bb8), I think.

**Comment by bmwill** [comment]
The solution would be to update the narwhal pointer in sui to a version which includes the grpc network changes so that we can use https://github.com/MystenLabs/narwhal/blob/main/types/src/generated/narwhal.rs#L395 to send transactions to narwhal as these tonic clients can be cheaply cloned and share the same underlying connection
