### ISSUE TITLE
[Gateway] Allow passing in either Object ID or ObjectRef for objects in transactions

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#1457]
Some Gateway APIs today pass object IDs as arguments, while some pass object refs. They are not consistent.
We want to always provide an option to pass object refs in case a user wants to specify exactly which version of object they want to operate on to prevent errors or accidentally using the wrong object version. It may also be a common need for users to not want to worry about version control and just want to use the latest version.
Hence we should make the argument flexible with two options, either ID or ref, and if it's ID the gateway will use the latest version.

**Comment by patrickkuo** [comment]
All the transaction creation methods are now taking `ObjectID`, currently we force client to use the latest object version because of this, in the future client can create the `TransactionData` on the client side using the SDK if they want more control on which object ref they want to use in a transaction.
