### ISSUE TITLE
Wallet sync can fail with no errors

### ISSUE THREAD

**Issue by mystenmark** [MystenLabs/sui#1523]
Its possible for the wallet sync step to fail without any errors. The root cause, as far as I can tell is that quorum_map_then_reduce_with_timeout https://github.com/MystenLabs/sui/blob/main/sui_core/src/authority_aggregator.rs#L291 can time out on every validator, and return a successful response with 0 entries.

**Comment by huitseeker** [comment]
`quorum_map_then_reduce_with_timeout` is a function composition operation, it would be great if you had the point of call (to see the `FMap`, `FReduce` arguments)

**Comment by lxfind** [comment]
So there are several issues in the current implementation that we should fix/improve:
1. First of all, we use 60s as the timeout for any query to validators. This is probably too long for DevNet. We should make it maybe 1s for DevNet so that we get quicker feedback on network issues.
2. Only transaction execution would check on the result of quorum, i.e. whether we got back enough to form a cert. For any other queries (in this case, sync account), we don't check how many validators responded, assuming that some could just drop and that's fine. In the extreme case when no validator responded, we just assumed that there is no data to sync. We should perhaps do two things here, first of all, emit warning if too many validators are dropping, and second, error if all dropped.
