### ISSUE TITLE
[Move] Enforce immutable/shared object at creation

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#1543]
Proposal for discussion: Should we require immutable and shared objects to be immutable/shared at creation, and not allow turning an owned object into immutable/shared latter?
There are a few potential issues to allow turning an owned object into immutable/shared:
If an object has child objects, then turning it into immutable would freeze all child objects. This could be a feature, but I think it's also a big risk for misuse. I cannot think of a scenario that people actually want to do this. The typical use case of immutable object should be some kind of immutable config/record on-chain for reference, and usually we want to create them as immutable at birth.
For shared objects, when programming the type, it will be very difficult to reason about the code if we need to assume that the object can be owned sometimes but also shared at other times. In all the use cases I have seen so far, we want an object to be shared at birth, and should never want to turn an owned object into shared latter.
What do you think?
What this means, is that immutability/being shared could potentially also be a static state of a type, instead of dynamic state. So ideally if we could somehow figure out a way to express a type to be "always immutable" or "always shared" in the language it would be even better. Then we could do a lot more things statically.

**Comment by gdanezis** [comment]
Its not because we can -- from a dist sys safety perspective -- transitions from owned to immutable to shared that we must. If you feel we do not lose any expresivity, then lets encode it in the type, and never change it -- and we can always provide explicit conversions if need be right? ( ie. fn freeze ( ObjOwned ) -> ObjImmutable )

**Comment by lxfind** [comment]
> Its not because we could -- from a dist sys safety perspective -- transition from owned to immutable to shared, that we must. 

Did you mean we must support transition from owned to immutable/shared object? Why is that?

**Comment by lxfind** [comment]
On immutable: I take it back. Enforcing immutable at creation is basically making immutability useless. One can simply define the type without any functions that can mutate the object. A more typical usecase, if any, with immutable object should be that an object used to be mutable and at some point people want to make it immutable. However, even this use case is a stretch. One can only mutate their own object. So what's the point of making their own object immutable?
Perhaps we really don't need immutable objects.

**Comment by gdanezis** [comment]
> Did you mean we must support transition from owned to immutable/shared object? Why is that?

No exactly the opposite. We are not obliged to support it if we think this is not needed to express interesting contracts.

What I was trying to say was: we have many option on safe things we can do from the perspective of the system (like the transitions you mention). This does not mean we must do them. We must only do them if they are useful to our users. Otherwise, the simpler the better (so no transitions in this case).

**Comment by gdanezis** [comment]
> Perhaps we really don't need immutable objects.

We totally need immutable objects. Like our contracts are immutable objects, and any object that needs to convey information to make users could be immutable to achieve this.

My understanding of your proposal was: we define a constructor for a type, and you can construct the object. But after that the object is immutable, and cannot be deleted. This is quite usual in programming no? Why would this not be useful?

**Comment by lxfind** [comment]
> > Perhaps we really don't need immutable objects.
> 
> We totally need immutable objects. Like our contracts are immutable objects, and any object that needs to convey information to make users could be immutable to achieve this.
> 
> My understanding of your proposal was: we define a constructor for a type, and you can construct the object. But after that the object is immutable, and cannot be deleted. This is quite usual in programming no? Why would this not be useful?

Contract will still be immutable. So the question is whether we need immutable Move objects.
It's fairly easy to enforce an immutable object without making it immutable: developer can simply not define any function that takes a mutable reference or by-value argument of this type. The compiler can even infer this and tell them: hey this type will never be mutated after creation. So I am trying to figure out what extra benefit we can provide by explicitly support the concept of an immutable object.
One use case may be that they want some object to be accessible (read-only) by everyone, but in a cheap way (not having to go to consensus), such as some kind of public record.

**Comment by gdanezis** [comment]
> One use case may be that they want some object to be accessible (read-only) by everyone, but in a cheap way (not having to go to consensus), such as some kind of public record.

yes, this is a crucial usecase. Now if the compiler can tag an object as immutable, in a way that we can infer it is immutable and allow it to be read by everyone, all the better.

**Comment by sblackshear** [comment]
A few thoughts:
- With the proposal we are considering to enable shared object deletion (`Sequencer` is the only shared object type + there's only one such object for now), I think the question about owned -> shared transitions goes away. There's only one magic shared object.
- However, any owned object can *effectively* become shared by becoming a direct or transitive child of a `Sequencer`.
- IMO, this single-owner vs effectively shared distinction should not be expressed statically because in practice this relationship is very dynamic. E.g., you might transfer a single-owner collection of NFT's (encoded as a parent-child hierarchy) to a shared marketplace to be sold, then a buyer might purchase the collection, making it a single owner object again. You do not want to force the seller to materialize all of the child objects in the collection and explicitly convert them into "shareables"--they should be able to transfer the collection directly to the NFT marketplace parent object with no conversions.

**Comment by lxfind** [comment]
> * With the proposal we are considering to enable shared object deletion (`Sequencer` is the only shared object type + there's only one such object for now), I think the question about owned -> shared transitions goes away. There's only one magic shared object.

There are some differences in these two approaches, and I wonder what the trade-offs are:
A: There is only one shared object, and any object that needs shared access will make the object a child of that single shared object, i.e. we only support introducing effectively shared object.
B: There is a shared object wrapper type. Any object that needs to be directly shared can be wrapped into this wrapper type. It is still possible to introduce effectively shared object by having a shared object own another object. i.e. we support both effectively shared object and directly shared object.

**Comment by sblackshear** [comment]
Good questions; here's how I would break it down (and am curious to hear your thoughts)

`Shared<T>`:
+ No need to include extra `Sequencer` object ID as input
+ Transfers of the `T` prevented by construction
- Not immediately clear to me how deleting the `T` would work
- Minor devex annoyance of needing to borrow the `T` instead of taking `&mut T` as input directly

`Sequencer`
+ Deletion seems more straightword because an entrypoint can get ownership of the child `T`
+ No need to explain conceptual distinction between shared and effectively shared (everything is effectively shared)
- Every shared object tx will need to include the `Sequencer` object ID as input
- Preventing transfer of the `T` requires dynamic checks (or new abilities)

**Comment by sblackshear** [comment]
Ah, I see--I think maybe I misunderstood `Shared<T>`. Is the idea that the `T` is phantom type + the "real" shared object is a child of `Shared<T>`?

**Comment by lxfind** [comment]
Oh no it will just be something like:
```
struct Shared<T> has key {
    id: VersionedID,
    object: T,
}
```
It's an object in itself, and wraps an object in it. But since it's an object, it can have child object, too.

**Comment by sblackshear** [comment]
Gotcha. In that case, I'd replace the "Not immediately clear to me how deleting the T would work" con with "Only partial deletion is possible".
