### ISSUE TITLE
error[Sui E01001]: invalid object constructionSui Code Bug or Feature Request

### ISSUE THREAD

**Issue by Shantanu505** [MystenLabs/sui#15966]
sui move build --force
UPDATING GIT DEPENDENCY https://github.com/MystenLabs/sui.git
INCLUDING DEPENDENCY Sui
INCLUDING DEPENDENCY MoveStdlib
BUILDING dep_package
error[Sui E01001]: invalid object construction
┌─ /Users/.move/https___github_com_MystenLabs_sui_git_framework__testnet/crates/sui-framework/packages/sui-framework/sources/random.move:53:20
│
53 │ let self = Random {
│ ╭────────────────────^
54 │ │ id: object::randomness_state(),
│ │ -- -------------------------- Non fresh UID from this position
│ │ │
│ │ The UID must come directly from sui::object::new. Or for tests, it can come from sui::test_scenario::new_object
55 │ │ inner: versioned::create(version, inner, ctx),
56 │ │ };
│ ╰─────────^ Invalid object creation without a newly created UID.

Failed to build Move modules: Compilation error.

Expected Result
When running sui move build --force can't compile.
same issue is coming when trying to compile using movestudio.

System Information
OS: windows
![image](https://github.com/MystenLabs/sui/assets/75172076/5e038b49-b4f1-469e-9999-3a65bc78aeb4)

Compiler: SUI testnet

**Comment by stefan-mysten** [comment]
Thanks for reporting this. The issue is that brew installs the most stable version, which corresponds to mainnet. Rarely, the testnet and devnet might introduce changes that break the CLI mainnet, which is what happened now because of the move verifier that was updated. We're actively working on ways to prevent this issue happening in the future.

As of now, we're updating brew to use the testnet version of the CLI. 

You might need to reinstall Sui from devnet or testnet to get rid of this error.

**Comment by stefan-mysten** [comment]
If this is still an issue, try:  `brew upgrade mystenlabs/tap/sui`
