### ISSUE TITLE
Sui Installation Error

### ISSUE THREAD

**Issue by hrsh22** [MystenLabs/sui#16167]
Steps to Reproduce Issue
after I ran:
cargo install --locked --git https://github.com/MystenLabs/sui.git --branch testnet sui

Result:
error: failed to run custom build command for `narwhal-types v0.1.0 (C:\Users\harsh\.cargo\git\checkouts\sui-6ac459c53b1b685a\673fcb2\narwhal\types)`

Caused by:
  process didn't exit successfully: `C:\Users\harsh\AppData\Local\Temp\cargo-install3Njyyh\release\build\narwhal-types-493f3c1afcce934e\build-script-build` (exit code: 1)
  --- stdout
  cargo:rerun-if-changed=proto/narwhal.proto
  cargo:rerun-if-changed=proto

  --- stderr
  Error: Custom { kind: PermissionDenied, error: "failed to invoke protoc (hint: https://docs.rs/prost-build/#sourcing-protoc): (path: \"D:\\\\protoc\\\\bin\"): Access is denied. (os error 5)" }
warning: build failed, waiting for other jobs to finish...
error: failed to compile `sui v1.18.0 (https://github.com/MystenLabs/sui.git?branch=testnet#673fcb2a)`, intermediate artifacts can be found at `C:\Users\harsh\AppData\Local\Temp\cargo-install3Njyyh`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

**Comment by hrsh22** [comment]
Hi @stefan-mysten , I am using Windows 11. Have already tried turning off windows defender and other versions of protocol buffers but nothing seems to work.

**Comment by stefan-mysten** [comment]
@hrsh22 ok, let's see if you have everything needed installed. Could you confirm that you have protobuf compiler installed and you can call `protoc` from terminal? See here: https://docs.sui.io/guides/developer/getting-started/sui-install#protocol-buffers

**Comment by hrsh22** [comment]
Yes it installed. 

C:\Users\harsh>protoc --version
libprotoc 26.0-rc1

**Comment by stefan-mysten** [comment]
Great. It is on the path, right?

Can you do a `rustup update` and then try again? Does that work?

**Comment by hrsh22** [comment]
Yes, it is on the path. Tried again after rust update but still the error persists.

![z](https://github.com/MystenLabs/sui/assets/90423812/67efb59f-9eff-4265-94c0-aa009620e6e6)

**Comment by SuiSunbeam** [comment]
This might help https://github.com/rust-lang/cargo/issues/11544#issuecomment-1491691403 although it sounds like you've already done this.

**Comment by hrsh22** [comment]
Yep, and have even turned off the windows defender.

![x](https://github.com/MystenLabs/sui/assets/90423812/15729193-7cf3-4bcd-ac8d-f48a273cb640)

**Comment by stefan-mysten** [comment]
The interesting error there is telling us that access is denied to bin folder where protoc exists. My intuition says that cargo either confuses the paths to `protoc` - as I can see that protoc is both in `D:\\\protoc\bin` and also in `C:\protoc\bin`. Can you maybe remove/rename the one in D? and try again? Or, maybe, add the `D:\protoc\bin` to the antivirus exclusion path (see fig 2).

Perhaps this StackOverflow post could help too: https://stackoverflow.com/questions/76981763/rust-cargo-build-error-access-is-denied-os-error-5

**Comment by hrsh22** [comment]
Issue got solved! 
The solution was to reinstall rust :)

**Comment by stefan-mysten** [comment]
@hrsh22 happy to hear that things worked out in the end, and thanks for your persistence.

**Comment by stefan-mysten** [comment]
Hard to know why it failed without more information - could you attach the error logs? I assume you're installing from `devnet` branch as you need to publish something on `devent`?

If you don't need to publish on devnet, try to install as per the docs: https://docs.sui.io/guides/developer/getting-started/sui-install

**Comment by Oloyede-Michael** [comment]
okay I've downloaded as per the doc and it brought up a new error:

warning: `sui-core` (lib) generated 1 warning
error: could not compile `sui-core` (lib); 1 warning emitted

Caused by:
  process didn't exit successfully: `/home/micheal/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc --crate-name sui_core --edition=2021 crates/sui-core/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=148 --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C panic=abort -C embed-bitcode=no -C debuginfo=1 -C split-debuginfo=packed --warn=unexpected_cfgs --cfg 'feature="test-utils"' --check-cfg 'cfg(docsrs)' --check-cfg 'cfg(feature, values("test-utils"))' --check-cfg 'cfg(msim)' --check-cfg 'cfg(fail_points)' -C metadata=8d98c5a19ff79e7e -C extra-filename=-8d98c5a19ff79e7e --out-dir /tmp/cargo-installAB7EmP/release/deps -C strip=debuginfo -L dependency=/tmp/cargo-installAB7EmP/release/deps --extern anemo=/tmp/cargo-installAB7EmP/release/deps/libanemo-f07c77177c7147c2.rmeta --extern anyhow=/tmp/cargo-installAB7EmP/release/deps/libanyhow-0ff6e9b11fdbb9c0.rmeta --extern arc_swap=/tmp/cargo-installAB7EmP/release/deps/libarc_swap-a97f9a0d0450156b.rmeta --extern async_trait=/tmp/cargo-installAB7EmP/release/deps/libasync_trait-1b70ae3b71d23f91.so --extern axum=/tmp/cargo-installAB7EmP/release/deps/libaxum-503bef01ad921300.rmeta --extern bcs=/tmp/cargo-installAB7EmP/release/deps/libbcs-db8b3b93769a00d9.rmeta --extern bytes=/tmp/cargo-installAB7EmP/release/deps/libbytes-39f94f0390221d38.rmeta --extern chrono=/tmp/cargo-installAB7EmP/release/deps/libchrono-c630c20db144503a.rmeta --extern consensus_config=/tmp/cargo-installAB7EmP/release/deps/libconsensus_config-7c9ce18a935a78bb.rmeta --extern consensus_core=/tmp/cargo-installAB7EmP/release/deps/libconsensus_core-ab0bf892a74832cc.rmeta --extern count_min_sketch=/tmp/cargo-installAB7EmP/release/deps/libcount_min_sketch-69306994cba33811.rmeta --extern dashmap=/tmp/cargo-installAB7EmP/release/deps/libdashmap-170a7308dd9c04f2.rmeta --extern diffy=/tmp/cargo-installAB7EmP/release/deps/libdiffy-1021dafa76af8582.rmeta --extern either=/tmp/cargo-installAB7EmP/release/deps/libeither-b8aaac46faaf16aa.rmeta --extern enum_dispatch=/tmp/cargo-installAB7EmP/release/deps/libenum_dispatch-eb6caa2e83456a89.so --extern eyre=/tmp/cargo-installAB7EmP/release/deps/libeyre-e7ebe84652a72f0c.rmeta --extern fastcrypto=/tmp/cargo-installAB7EmP/release/deps/libfastcrypto-8a73f5dc09327621.rmeta --extern fastcrypto_tbls=/tmp/cargo-installAB7EmP/release/deps/libfastcrypto_tbls-fc3e14863046961e.rmeta --extern fastcrypto_zkp=/tmp/cargo-installAB7EmP/release/deps/libfastcrypto_zkp-e709c89f863d9d56.rmeta --extern futures=/tmp/cargo-installAB7EmP/release/deps/libfutures-f9cff567a197e4b0.rmeta --extern im=/tmp/cargo-installAB7EmP/release/deps/libim-3e1fb8c129f60b19.rmeta --extern indexmap=/tmp/cargo-installAB7EmP/release/deps/libindexmap-1bdbc3450bae325b.rmeta --extern itertools=/tmp/cargo-installAB7EmP/release/deps/libitertools-760789d28bf9af6e.rmeta --extern jsonrpsee=/tmp/cargo-installAB7EmP/release/deps/libjsonrpsee-903fa4648a5a06d5.rmeta --extern lru=/tmp/cargo-installAB7EmP/release/deps/liblru-5689160e6b4bee1c.rmeta --extern mockall=/tmp/cargo-installAB7EmP/release/deps/libmockall-e19bcde2fa678fd3.rmeta --extern moka=/tmp/cargo-installAB7EmP/release/deps/libmoka-7e5cbb3246283965.rmeta --extern move_binary_format=/tmp/cargo-installAB7EmP/release/deps/libmove_binary_format-45aea91e94dfa877.rmeta --extern move_bytecode_utils=/tmp/cargo-installAB7EmP/release/deps/libmove_bytecode_utils-ebe415dfaa3085b5.rmeta --extern move_core_types=/tmp/cargo-installAB7EmP/release/deps/libmove_core_types-d0882e0ee5ed057b.rmeta --extern move_package=/tmp/cargo-installAB7EmP/release/deps/libmove_package-af8d4be2c7be971f.rmeta --extern move_symbol_pool=/tmp/cargo-installAB7EmP/release/deps/libmove_symbol_pool-ba7208f08b16e9db.rmeta --extern mysten_common=/tmp/cargo-installAB7EmP/release/deps/libmysten_common-cfce6cf7a31e5d30.rmeta --extern mysten_metrics=/tmp/cargo-installAB7EmP/release/deps/libmysten_metrics-7c573f5d01e8e725.rmeta --extern mysten_network=/tmp/cargo-installAB7EmP/release/deps/libmysten_network-193cf43592d9c37f.rmeta --extern narwhal_types=/tmp/cargo-installAB7EmP/release/deps/libnarwhal_types-a6057ecae82c7c04.rmeta --extern nonempty=/tmp/cargo-installAB7EmP/release/deps/libnonempty-0e9bdf3c53bfec53.rmeta --extern num_cpus=/tmp/cargo-installAB7EmP/release/deps/libnum_cpus-7d7b295b90e5265a.rmeta --extern object_store=/tmp/cargo-installAB7EmP/release/deps/libobject_store-ebebfd03051f6977.rmeta --extern once_cell=/tmp/cargo-installAB7EmP/release/deps/libonce_cell-f2a195eef89a08c6.rmeta --extern parking_lot=/tmp/cargo-installAB7EmP/release/deps/libparking_lot-80d76d8a3841ac28.rmeta --extern prometheus=/tmp/cargo-installAB7EmP/release/deps/libprometheus-31e6557fd7133024.rmeta --extern rand=/tmp/cargo-installAB7EmP/release/deps/librand-d424d9f0964f3e4a.rmeta --extern rayon=/tmp/cargo-installAB7EmP/release/deps/librayon-49fcd00860fdd294.rmeta --extern reqwest=/tmp/cargo-installAB7EmP/release/deps/libreqwest-1f87be9ffa03aa29.rmeta --extern roaring=/tmp/cargo-installAB7EmP/release/deps/libroaring-b963b2f28c219e93.rmeta --extern scopeguard=/tmp/cargo-installAB7EmP/release/deps/libscopeguard-6be9da387277153c.rmeta --extern serde=/tmp/cargo-installAB7EmP/release/deps/libserde-9f6702ade7968282.rmeta --extern serde_json=/tmp/cargo-installAB7EmP/release/deps/libserde_json-a00cf9736f6ebe2c.rmeta --extern serde_with=/tmp/cargo-installAB7EmP/release/deps/libserde_with-3c17a481f912e315.rmeta --extern shared_crypto=/tmp/cargo-installAB7EmP/release/deps/libshared_crypto-5be9fb410726eefb.rmeta --extern signature=/tmp/cargo-installAB7EmP/release/deps/libsignature-170ea944e9995075.rmeta --extern static_assertions=/tmp/cargo-installAB7EmP/release/deps/libstatic_assertions-54d6e1a888617d70.rmeta --extern sui_archival=/tmp/cargo-installAB7EmP/release/deps/libsui_archival-62e67fd5015ce8f3.rmeta --extern sui_authority_aggregation=/tmp/cargo-installAB7EmP/release/deps/libsui_authority_aggregation-0ed8a2aa8b37c490.rmeta --extern sui_config=/tmp/cargo-installAB7EmP/release/deps/libsui_config-1472829f46fba66d.rmeta --extern sui_execution=/tmp/cargo-installAB7EmP/release/deps/libsui_execution-3f90ee2a2a441617.rmeta --extern sui_framework=/tmp/cargo-installAB7EmP/release/deps/libsui_framework-80cee308ab884a95.rmeta --extern sui_genesis_builder=/tmp/cargo-installAB7EmP/release/deps/libsui_genesis_builder-47f12814c49cc037.rmeta --extern sui_json_rpc_types=/tmp/cargo-installAB7EmP/release/deps/libsui_json_rpc_types-e6949664b2439739.rmeta --extern sui_macros=/tmp/cargo-installAB7EmP/release/deps/libsui_macros-1047675fe41901cd.rmeta --extern sui_move_build=/tmp/cargo-installAB7EmP/release/deps/libsui_move_build-79fd87ef254dcdd5.rmeta --extern sui_network=/tmp/cargo-installAB7EmP/release/deps/libsui_network-8c7a4aa908a0d1f3.rmeta --extern sui_protocol_config=/tmp/cargo-installAB7EmP/release/deps/libsui_protocol_config-cc36cb7d408cc9c8.rmeta --extern sui_simulator=/tmp/cargo-installAB7EmP/release/deps/libsui_simulator-15583d8f507e525b.rmeta --extern sui_storage=/tmp/cargo-installAB7EmP/release/deps/libsui_storage-8bf97a35618e2a52.rmeta --extern sui_swarm_config=/tmp/cargo-installAB7EmP/release/deps/libsui_swarm_config-8d7994b806d4c6b2.rmeta --extern sui_tls=/tmp/cargo-installAB7EmP/release/deps/libsui_tls-0153a47b367acf38.rmeta --extern sui_transaction_checks=/tmp/cargo-installAB7EmP/release/deps/libsui_transaction_checks-b0237b6f35092244.rmeta --extern sui_types=/tmp/cargo-installAB7EmP/release/deps/libsui_types-c493fc1962459295.rmeta --extern tap=/tmp/cargo-installAB7EmP/release/deps/libtap-30aeb9b50c438068.rmeta --extern telemetry_subscribers=/tmp/cargo-installAB7EmP/release/deps/libtelemetry_subscribers-8e55d6ebe20467d8.rmeta --extern tempfile=/tmp/cargo-installAB7EmP/release/deps/libtempfile-135b4a074fab7b1b.rmeta --extern thiserror=/tmp/cargo-installAB7EmP/release/deps/libthiserror-439e976065b51d30.rmeta --extern tokio=/tmp/cargo-installAB7EmP/release/deps/libtokio-70e82aa81faddc1a.rmeta --extern tokio_retry=/tmp/cargo-installAB7EmP/release/deps/libtokio_retry-72847a4d31a51c52.rmeta --extern tokio_stream=/tmp/cargo-installAB7EmP/release/deps/libtokio_stream-6e4665b2c3dc7ac5.rmeta --extern tracing=/tmp/cargo-installAB7EmP/release/deps/libtracing-8bb9b84d43b52d86.rmeta --extern twox_hash=/tmp/cargo-installAB7EmP/release/deps/libtwox_hash-2ce8c62c24505a9a.rmeta --extern typed_store=/tmp/cargo-installAB7EmP/release/deps/libtyped_store-ed5c90404cd27c6e.rmeta --extern zeroize=/tmp/cargo-installAB7EmP/release/deps/libzeroize-ae9a5855efd9d617.rmeta -L native=/tmp/cargo-installAB7EmP/release/build/ring-1343df71e3843246/out -L native=/tmp/cargo-installAB7EmP/release/build/blst-feda5580d80f3bd3/out -L native=/tmp/cargo-installAB7EmP/release/build/secp256k1-sys-0c6333d6f0faba8e/out -L native=/tmp/cargo-installAB7EmP/release/build/zstd-sys-4786dd7c62130056/out -L native=/tmp/cargo-installAB7EmP/release/build/ring-e06eac5450b4a80d/out -L native=/tmp/cargo-installAB7EmP/release/build/psm-1a25e7f3ad459fc7/out -L native=/tmp/cargo-installAB7EmP/release/build/librocksdb-sys-1b34ad90a0f8f04a/out -L native=/tmp/cargo-installAB7EmP/release/build/librocksdb-sys-1b34ad90a0f8f04a/out -L native=/tmp/cargo-installAB7EmP/release/build/libz-sys-4570ac96a0b49d45/out/lib -L native=/tmp/cargo-installAB7EmP/release/build/libz-sys-4570ac96a0b49d45/out/lib -L native=/tmp/cargo-installAB7EmP/release/build/lz4-sys-96ea79c5b23e2ad2/out` (signal: 9, SIGKILL: kill)
warning: build failed, waiting for other jobs to finish...
error: failed to compile `sui v1.38.2 (https://github.com/MystenLabs/sui.git?branch=testnet#99fcadf4)`, intermediate artifacts can be found at `/tmp/cargo-installAB7EmP`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

**Comment by stefan-mysten** [comment]
Have you tried using the binaries instead of installing from source? https://github.com/MystenLabs/sui/releases/tag/testnet-v1.38.2

From the log I can only see a bunch of linking, so not really useful. Might be some dependencies that are missing. 
Might want to try this
`sudo apt-get install curl git-all cmake gcc libssl-dev pkg-config libclang-dev build-essential`

**Comment by Oloyede-Michael** [comment]
okay sui has been installed. Thank you

**Comment by iscsean** [comment]
内存太小了，内存调大些，最好8G以上。
