### ISSUE TITLE
Type 0x2::kiosk::Kiosk is not registered

### ISSUE THREAD

**Issue by sudofina** [MystenLabs/sui#17256]
## Steps to Reproduce Issue

kioskClient.getKiosk(kioskId) where kioskId is 0x6ca6a0fbcd8bb6952382aa0f590c8ab9c46d102d6704e186a6cc0a1c235d524d on testnet: https://testnet.suivision.xyz/object/6ca6a0fbcd8bb6952382aa0f590c8ab9c46d102d6704e186a6cc0a1c235d524d 

## Expected Result

Expected getKiosk to return the kiosk data.

## Actual Result

An error was returned:
```
"Error: Type 0x2::kiosk::Kiosk is not registered\n    at _BCS.getTypeInterface (http://localhost:3000/static/js/bundle.js:122705:13)\n    at _BCS.de (http://localhost:3000/static/js/bundle.js:122202:19)\n    at getKioskObject 
```

## System Information
```
"@mysten/bcs": "0.11.1",
"@mysten/sui.js": "0.51.2",
"@mysten/kiosk": "0.8.6",
```

**Comment by sudofina** [comment]
Looks like the error is coming out of:
https://github.com/MystenLabs/sui/blob/main/sdk/bcs/src/legacy-registry.ts#L947

which is called from:
https://github.com/MystenLabs/sui/blob/main/sdk/bcs/src/legacy-registry.ts#L274

**Comment by EasonC13** [comment]
Have you specified that you want to call a testnet kiosk?

**Comment by sudofina** [comment]
Yes, that's specified. 

My code:
```
const kioskClient = new KioskClient({
      suiClient,
      network: Network.TESTNET,
});

const res = await kioskClient.getKiosk({
   id: kioskId,
   options: {
         withKioskFields: true,
         withObjects: true,
    },
});
```

But I found out that this error only occurs when I provide `withKioskFields = true` option to the getKiosk API since when `withKioskFields` is set to true, it will call `getKioskObject` which internally calls `bcs.de` in https://github.com/MystenLabs/sui/blob/main/sdk/bcs/src/legacy-registry.ts#L274, which has led to the error in `legacy-registry.ts`: https://github.com/MystenLabs/sui/blob/main/sdk/bcs/src/legacy-registry.ts#L947.

I am able to get the response back without the error if I remove `withKioskFields: true` from the provided option.

**Comment by sudofina** [comment]
I am able to get what I want for now but I will leave this issue open as I believe this is still an issue if we want to set `withKioskFields = true'

**Comment by hayes-mysten** [comment]
This may be related to the `sideEffects` option, which is set to `false` here: https://github.com/MystenLabs/sui/blob/4313fc26cbc00ca3ecdb7702e709b55349fa2783/sdk/kiosk/package.json#L17. This option allows bundlers to remove code that isn't directly imported, reducing bundle size.  The bcs type it's complaining about is registered here: https://github.com/MystenLabs/sui/blob/4313fc26cbc00ca3ecdb7702e709b55349fa2783/sdk/kiosk/src/bcs.ts#L14-L20, but I suspect is being eliminated during bundling.

There is some existing work that entirely removes the bcs registry and ensures that the SDKs aren't dependent on types being registered as a side-effect of importing files.  If this is a blocker, we can probably temporarily set `sideEffects` to `true` in the kiosk package, otherwise, this will be resolved in an upcoming release that should be out in the next few weeks

**Comment by hayes-mysten** [comment]
The registry has been removed from @mysten/bcs, and the kiosk sdk has been updated to use the updated bcs APIs, so this should no-longer be an issue
