### ISSUE TITLE
Sui Dapp Kit Nextjs App router support 

### ISSUE THREAD

**Issue by RevanthGundala** [MystenLabs/sui#17794]
## Steps to Reproduce Issue

Install dependencies from @mysten/dapp-kit and wrap app with <WalletProvider>

## Actual Result

```
app-index.js:33 Warning: Cannot render a <style> outside the main document without knowing its precedence and a unique href key. React can hoist and deduplicate <style> tags if you provide a `precedence` prop along with an `href` prop that does not conflic with the `href` values used in any other hoisted <style> or <link rel="stylesheet" ...> tags.  Note that hoisting <style> tags is considered an advanced feature that most will not use directly. Consider moving the <style> tag to the <head> or consider adding a `precedence="default"` and `href="some unique resource identifier"`, or move the <style> to the <style> tag.
```

## System Information

* OS: MacOS

## Additional Info

I suspect this is happening because of the Theme prop from the WalletProvider. Since styles can only be applied in the head for Nextjs, I cannot wrap my App Component with the provider without encountering errors. Would like to know if there's any workaround for this.

**Comment by williamrobertson13** [comment]
Hey @RevanthGundala! Thanks for the report, I just merged https://github.com/MystenLabs/sui/commit/3f8b08dedcffb9341930e387c230fa03e520b22a which should resolve this issue for you. We're going to cut a new release of `dapp-kit` today, so be on the lookout for `v0.13.2`! In the meantime if you don't want to wait, you can move the `WalletProvider` component so that it's rendered inside the `body` element which should also fix the error you're seeing.
