### ISSUE TITLE
[Kiosk] Feature request for concurrent actions against a Kiosk

### ISSUE THREAD

**Issue by Sceat** [MystenLabs/sui#18234]
Originally posted for personal kiosks https://github.com/MystenLabs/apps/issues/47

Could the Kiosk standard be improved to support concurrent access ? The owner of the kiosk cap could potentially clone his kioskOwnerCap in an entry function (to avoid breaking personalKiosk etc..), allowing to have a pool of keys to mutate the kiosk.

In a game relying on Kiosk, the UX is greatly improved if the user doesn't need to wait each transaction (which can takes some time when waiting for events / sponsoring)

- batch listing/unlisting items
- crafting
- selecting characters
- destroying / sending 

It isn't very intuitive for a player to select all actions to then "confirm" them in a single ptb

_ps: my kioskOwnerCap got equivocated after playing too fast_

**Comment by damirka** [comment]
Hey @Sceat, sorry for delay on this one. If you need to have multiple capabilities that have control over Kiosk, you can wrap the `KioskOwnerCap` into a shared object that would grant the callee access to the underlying Cap. It's not the case for `PersonalKioskCap` though!

But it seems to me that the issue you're trying to prevent is [Object Equivocation](https://sdk.mystenlabs.com/typescript/owned-object-pool/overview), and it needs to have better handling on the client rather than in the module.

**Comment by damirka** [comment]
It's not an issue that should be handled in Move. Object equivocation applies to all objects, including gas.
