### ISSUE TITLE
Sui dApp Kit: It's not possible to switch from one Sui address to another through the ConnectButton control

### ISSUE THREAD

**Issue by kkomelin** [MystenLabs/sui#18507]
## Problem/Motivation

1. I connect my app https://demo.sui-dapp-starter.dev/ to the Sui Wallet with address 1.
2. I switch to another address (address 2) through the Sui Wallet. The ConnectButton control in the app doesn't react in any way and still displays address 1.
3. I disconnect from the Sui Wallet through the ConnectButton control.
4. I connect to the Sui Wallet through the ConnectButton control again.
5. The ConnectButton control connects me to the previous address (address 1). In its selectbox, I can only see one address (address 1).

Clearing all app data through Google Developer Tools -> Application -> Storage -> Clear site data doesn't help.

It looks like it's not currently possible to switch to another address through the ConnectButton control. Is it an expected behavior?

**Comment by Jordan-Mysten** [comment]
This is expected, the state of the wallet and the state of the dapp are intended to be fully decoupled, so that switching in one does not switch in the other.

For switching the connected addresses in the case that you don't select the right addresses to begin with, you currently would need to remove the connection from the wallet (you can do this in the "Apps" section), then trigger a connection from the dapp. In the future, we're planning on making the dapp disconnect action also forget the connection on the wallet side, which should make this a bit easier.

**Comment by kkomelin** [comment]
Thank you @Jordan-Mysten,

> This is expected, the state of the wallet and the state of the dapp are intended to be fully decoupled, so that switching in one does not switch in the other.

If the wallet stores the app user registration "permanently", the states don't look fully decoupled to me.

> For switching the connected addresses in the case that you don't select the right addresses to begin with, you currently would need to remove the connection from the wallet (you can do this in the "Apps" section)

That's not super-straightforward/easy for the end-user.

Some people use multiple addresses for security purposes. Simple example - one address for everyday use (games, contests, casinos) and another address for storing assets longer, for example receiving a salary/grant/bounty.

One of the problems which UX design solves is it makes the user interface predictable/intuitive for the end-user or in other words similar to what the user is already familiar with. Many users come to Sui from ETH (and Metamask). Even if supposedly we don't like how Metamask work, we have to use it as a base/prototype for smoother user transition to the Sui network, and Metamask lets user switch between addresses easily.

Currently, the selectbox in the ConnectButton is misleading. Why do we need a selectbox there? We can have just a disconnect button next to the address if we only allow one address at a time.

Can I ask you to consider prioritizing making the Disconnect button work as users expect - remove that permanent connection data from the wallet completely? Otherwise, why do we need the Disconnect button at all?

**Comment by hayes-mysten** [comment]
> Can I ask you to consider prioritizing making the Disconnect button work as users expect - remove that permanent connection data from the wallet completely? Otherwise, why do we need the Disconnect button at all?

This is how it works in the mobile wallet, and the extension wallet will match this behavior in the not too distant future.  As you mentioned, having separate addresses is something that is done for security, which is why we won't expose addresses the user didn't select in the original connection request to the dapp to select from.

What we can do (as you suggest) is clear the connected state on a disconnect, and when the user re-connects they can select a new address (or set of addresses).  I don't have an exact timeline, but this change is coming to the extension version of the wallet

**Comment by kkomelin** [comment]
Thank you @hayes-mysten!
