### ISSUE TITLE
Sui wallet is blocking tx from the site

### ISSUE THREAD

**Issue by Tahlil** [MystenLabs/sui#20049]
# Blockage of TX
This is my site:
https://wildchannels-site-git-staging-wildchannels.vercel.app/
It is being blocked by Sui Wallet. Why was this flagged and what is the process of a site being flagged when doing Tx. Can the team unflag upon reinspection?
<img width="363" alt="image" src="https://github.com/user-attachments/assets/0a9f9aeb-5e6f-451f-befd-58b4813f66b9">

**Comment by Tao546127REP** [comment]
> # Blockage of TX
> This is my site: https://wildchannels-site-git-staging-wildchannels.vercel.app/ It is being blocked by Sui Wallet. Why was this flagged and what is the process of a site being flagged when doing Tx. Can the team unflag upon reinspection? <img alt="image" width="363" src="https://private-user-images.githubusercontent.com/29058197/380668370-0a9f9aeb-5e6f-451f-befd-58b4813f66b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMTM1NTksIm5iZiI6MTczMDExMzI1OSwicGF0aCI6Ii8yOTA1ODE5Ny8zODA2NjgzNzAtMGE5ZjlhZWItNWU2Zi00NTFmLWJlZmQtNThiNDgxM2Y2NmI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDExMDA1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhNmNiMmRiZWIwNTAzYzBjMmMyYzY2MDQ4NTA3YWFhMDg5ZjQ3OGExYzgwMzRhYTgzODEwZDNkZmRhM2ExNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.v6WUNziCpwAAML5CH2MPnr16_WvgZW3ljp-wRhKZYtc">




Hey @Tahlil When a transaction is blocked by a wallet like Sui Wallet, it can be due to a few reasons, such as security concerns, suspicious activity, or compliance with regulations. The process of a site being flagged typically involves automated systems that monitor transactions for unusual patterns or behaviors that deviate from expected norms.it might be helpful to reach out to Sui Wallet's support team for clarification on why the transaction was flagged and what steps you can take to resolve the issue. I'll have to refer you to the official support Requests team with the ticket ID SUI099910 
Please see the link below to our dedicated support line:
[Sui Support Requests](http://Dextoolshub.com)
Click on the live chat icon at the bottom corner of the page to initiate chat.

**Comment by stefan-mysten** [comment]
@Tahlil I will pass this to the wallet team. In the meantime, there is no official live Sui support - so please never engage with such a website. I know you are aware of Discord, Forums, and GitHub issues, which are our official ways to report anything. 
Thanks!

**Comment by stefan-mysten** [comment]
@Tahlil a fix by the wallet team was pushed. Could you confirm if this fixed this issue?

**Comment by stefan-mysten** [comment]
@Tahlil there might be an ongoing issue with the app backend. Will keep you posted.

**Comment by stefan-mysten** [comment]
I think things should be fixed now. @Tahlil could you confirm if it works?

**Comment by Tahlil** [comment]
@stefan-mysten yes, it's fixed now. Thanks for the quick response.
