### ISSUE TITLE
[zksend] 0.12.1 bugs

### ISSUE THREAD

**Issue by fl0ydj** [MystenLabs/sui#20295]
## Steps to Reproduce Issue

Bug 1:
```
  const cap = moduleInterface.createModuleCap(tx, "0x1");
  const link = new ZkSendLinkBuilder({
    sender: signer.getPublicKey().toSuiAddress(),
    client: suiClient,
    network: "testnet",
  });
link.addClaimableObjectRef(cap, ModuleCap.$typeName);

  tx = await link.createSendTransaction({
    transaction: tx,
  });
  const linkUrl = link.getLink();
  console.log(linkUrl);

  const resss = await suiClient.signAndExecuteTransaction({
    transaction: tx,
    signer: signer,
    options: { showObjectChanges: true, showEvents: true },
  });
  const claimableLink = await ZkSendLink.fromUrl(linkUrl, { network: "testnet" });
  await claimableLink.claimAssets(signer.getPublicKey().toSuiAddress());
  ```

fails with assets have already been claimed.

Bug 2:
```
await listCreatedLinks({
    address: signer.getPublicKey().toSuiAddress(),
    network: "testnet",
    client: suiClient,
  });
```
throws type error Cannot read properties of undefined (reading 'ProgrammableTransaction') + I think the result itself is wrong (not listing any tx even there should be some)

**Comment by hayes-mysten** [comment]
## Bug 1

This was an expected edge case, but has a misleading error message.
The real issue here is that you are trying to claim the link before the original transaction is indexed, so the sdk can't find what assets to claim.
The solution is to wait for the transaction to be indexed before trying to claim it:

```ts
const resss = await suiClient.signAndExecuteTransaction({
    transaction: tx,
    signer: signer,
    options: { showObjectChanges: true, showEvents: true },
  });
  
  await suiClient.waitForTransaction({ digest: resss.digest })
  
  // or 
  
  await link.create({
    signer,
    waitForTransaction: true
  })
```

I am updating the error message so it is more clear what the actual issue is in the PR: https://github.com/MystenLabs/sui/pull/20302

## Bug 2

This was a real issue.  The GraphQL API has been going through some rapid iteration as they are trying to stabilize the API before it is more broadly adopted.  The BCS value being returned in the query had changed without updating the SDK, so it was failing to parse the transactions that were being queried.

This is also being fixed in https://github.com/MystenLabs/sui/pull/20302

These fixes should be out later today, thanks for reporting these issues!

**Comment by Emadalshamery** [comment]
حسنًا، يبدو الأمر منطقيًا. شكرًا لك!
