### ISSUE TITLE
splitCoins can not iterator

### ISSUE THREAD

**Issue by beykery** [MystenLabs/sui#20642]
const sps = txb.splitCoins(coin, amounts); 
   for (const item of sps) {
     .... ....
   }
   
   the 'for' loop can not be ended  , why ?  'sps' with unlimited length  ?

**Comment by hayes-mysten** [comment]
The sdk currently returns an infinite iterator for any result type.  This is because the result type is shared between commands like splitCoins and the moveCall command.  For move calls we don't actually know the number of nested results are unknown until after the transaction executes.

For splitCoins specifically, we should be able to know the number of coins created, but currently we haven't special-cased this, so it returns the same infinite iterator used by the moveCall command.

**Comment by beykery** [comment]
the iterator of split return , it's length can be known from the param 'amounts' .  so this can be fixed , am i right  ?
@hayes-mysten

**Comment by hayes-mysten** [comment]
Yes, this is something that can be fixed
