### ISSUE TITLE
[full node] Merge Validator & Full Node Binaries

### ISSUE THREAD

**Issue by oxade** [MystenLabs/sui#2068]
Since full nodes are a precursor to becoming validators, it makes sense to ship one binary which starts as a full node and can evolve as needed

**Comment by mystenmark** [comment]
(pasting my comments from the slack thread on this: https://mysten-labs.slack.com/archives/C03AW7J5Q5U/p1652906469866469)

There are already a bunch of existing differences between full node and validator:

* full node has additional indexes (https://github.com/MystenLabs/sui/pull/2053) that a lot of people felt shouldn’t be part of the validator
* full node is shortly going to use tx replaying instead of object syncing in its follower implementation - will validator also switch to tx replaying?
* full node serves the read-only gateway api, and according to [@Xun Li](https://mysten-labs.slack.com/team/U02P9CDJZDX) will also become the write side of the gateway.
   * this raises further questions about the role of gateway as a sparse-but-long-lived app-specific data store vs the role of a node as a complete-but-shorter-lived universal data store. [@Sam Blackshear](https://mysten-labs.slack.com/team/U02CJ362G5B) was asking about this in a different thread yesterday

managing these differences within a single process (e.g. turning off extended indexing when the node becomes a validator) is possible but it doesn’t seem like the easiest way to proceed to me (edited)

**Comment by Clay-Mysten** [comment]
Hi Ade, can we use this diagram in the full node docs?
https://mysten-labs.slack.com/archives/C03AW7J5Q5U/p1652906469866469
