### ISSUE TITLE
Define Sui support model for end users (and all)

### ISSUE THREAD

**Issue by Clay-Mysten** [MystenLabs/sui#2152]
Hi team,

For the Browser Extension Wallet launch, we hope to have the ability to link into distinct, finite articles answering common queries about the new interface from end users (rather than developers). See this for details:
http://go/browser-extension-wallet

Chris is thinking of something like:
https://nearhelp.zendesk.com/hc/en-us/articles/6185029842967-How-do-I-change-my-2FA-method-on-my-wallet-

Which got me wondering if we have considered using Zendesk. Which then got us wondering if we've started developing a support model. And so hence this issue.

What is the Sui support model for end users?

For developers we have docs.sui.io and Discord (as well as a various email lists that are not widely known). But even those folks, investors, and creators would benefit from some well-defined support process.

So what is it? Adding a slew of folks to start stewing on this. Whatever we do, we cannot have our engineers supporting folks forever...

**Comment by janetwu11** [comment]
AFAIK public blockchain support tends to rely on the open ecosystem and the community hub instead of more traditional customer support like Zendesk.  Wallet companies have different business models - they seem to generate revenue with an affiliate model by directing users to other exchanges or swaps, so Zendesk may be appropriate. We are building a production-level Wallet but I think its primary goal is to enable/bootstrap the Sui ecosystem and to showcase Sui differentiators; it is a non-goal to compete or draw users from other wallets. I imagine as we roll out new features on the chain, Sui Wallet may be the first to support new features (and have issues with new features) vs it will take time for other partner wallets in the ecosystem to catch up. In my mind for the Sui wallet we should have 1) a robust set of FAQs hosted by Mysten 2) a dedicated Discord channel to report or discuss Wallet issues (which to start will be monitored by social media mods and agency) 3) GitHub issues with appropriate bug reporting template & labels that our engineering team can triage. If at some point the Sui Wallet becomes very popular and is very widely adopted it may make sense to something like Zendesk. Would love to hear other thoughts as I don't consider myself a crypto native (yet).

**Comment by adeabiodun** [comment]
+1 on this Janet.
