### ISSUE TITLE
[data model] Eliminate version from client <-> authority write API’s 

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#218]
From #176:

In terms of what the authority handle_order and handle_certificate expect we can indeed remove the version from objects and only keep the (object_id, digest). In fact we could even play more tricks and keep a short object_id[:8] and digest, on the basis that there will be very few collisions. But that adds complexity for a few bytes (which we have no indication are the perf bottleneck now).

I am more hesitant in what we return to the client to be honest. Should we drop the versions from the objects mutated and deleted there as well? It is true however that if the client downloads them, they will get the version. So why not, lets do it.

I would keep of course the full ref in internal authority structures for the moment. We can drop them later if they are not used by sync.

**Comment by velvia** [comment]
Update: Was just having a discussion with @sblackshear.  Basically, from a data model point of view, we really want to decide on what is the "primary key" of an object, and just send that.  To send other bits of that is redundant.   What is the primary key?  To me it is either (ObjID, version) or (ObjDigest).   

(from me) So you want to send (ObjID, ObjDigest) and leave out the middle version.  Why not just send (ObjDigest) or is that not unique enough?  Anyways I know there's a doc on this, so I'll comment there

(from Sam) ObjDigest would be unique enough, but it would not give the authority enough info to find the object. Its store is keyed by object ID.
[@Evan Chan](https://mysten-labs.slack.com/team/U031EUNEWJE): your question makes me think, though. I don't think there's any enormous blocker to re-keying the authority's store + using only ObjDigest if we really wanted to. The ability to serve get_object_by_id queries would disappear, but authorities will (presumably) never be serving reads via those API's in the long term anyway (only full nodes)

From the object storage perspective, it also makes no sense to use the entire ObjectRef as a key.  You use the shortest and smallest possible primary key, and everything else can be indexed.  If the digest can be the unique ID and is guaranteed not to clash (this is to me the biggest question), then we should just use the digest everywhere, including in transactions, and as the storage key.  We can add an index to map from (ObjectID, version) to digest.   Locking should also then just use the digest.  Using the same primary key everywhere makes the system much more consistent.

Currently using the objectID only as the object key is dangerous because it means writes are not idempotent and there is much more care needed to be really safe.  It also makes caching much more difficult.   I will start a separate issue to change that.

**Comment by velvia** [comment]
Wrote an issue for storage being keyed on ObjectDigest alone - https://github.com/MystenLabs/sui/issues/1318
