### ISSUE TITLE
Wallet-ext: testnet feature scoping

### ISSUE THREAD

**Issue by 666lcz** [MystenLabs/sui#2186]
Starting points:

- education screens
    - request coin
    - gas
    - what is sui
    - linked from different places
- background process
    - p1
- session management
    - password
- Help center & operations
- contact list
- account recovery
    - buttons in app
- welcome screen
- pricing
- DApp <> Wallet
    - building a DApp
        - counter
    - Standardized “Connect Wallet” widget
    - expose an API for DApps to call
- multi address support
- UI Redesign
- network selection
- Transactions history(for the given wallet address)
- secure key storage
- p2p transfer flow

**Comment by janetwu11** [comment]
Thank you Chris! Sam and I had a discussion about the strategic goal of the Sui Wallet. Sam and I aligned on the following in:
- tablestakes functionality to enable the ecosystem for MainNet launch
- long-term be the primary wallet that would support the most advanced Sui features as they become ready; third-party wallets would typically take longer to catch up
- for MainNet launch showcase Sui differentiators. The two most substantial differentiator that came up are 'human-readable signing requests" (since in Sui what objects are involved in a transaction are ahead of time, it would be possible to display to the users that objects would get modified by the transaction before the user agrees to signing), which is something other blockchains cannot do today. The other one involves gasless transactions (the equivalent of meta transactions in Ethereum) which our Wallet should also support. Sam is going to write up something about both gasless transactions and human readable signing request. We should add both of these to the list.

**Comment by 666lcz** [comment]
Figure out the high-pri items for design agency

**Comment by gegaowp** [comment]
put up a doc here
https://www.notion.so/mystenlabs/TestNet-draft-Sui-wallet-roadmap-f3f992dd4b6c42f98420ab0551889bfa
plan to filter, prioritize and assign on Th.
