### ISSUE TITLE
Error acquiring lock for object(s), for transactions made in quick succession

### ISSUE THREAD

**Issue by MaithreyaSitaraman** [MystenLabs/sui#2386]
I am programmatically making transactions (in quick successsion) (obtaining txbytes via API calls in quick succession). I store those txbytes and am signing, executing them later. 

However, when I make two transactions in quick succession and attempt to execute them later, only the first transaction can be executed. When executing the other transaction, I get an error of the form:

`"message" : "Error acquiring lock for object(s): [UnexpectedSequenceNumber { object_id: 0x7a71f7380b4faec7d38580b1fb62b404ff168258, expected_sequence: SequenceNumber(22), given_sequence: SequenceNumber(21)`

**Comment by gdanezis** [comment]
Hi @MaithreyaSitaraman -- many thanks for the report. I triaged this as a bug, and I think it relates to a number of other issues filled.

Quick question if you can provide more context: 
* I presume the second transaction contains objects mutated by the first one, or shares the same gas object? Is that right?
* If you try to re-execute the second transaction, does it eventually execute, or do you get again an error?

**Comment by MaithreyaSitaraman** [comment]
Hi @gdanezis ,

-> The second transaction shares the same gas object with the first object
-> I will test it out again later today, but my impression from memory was that I again got the error when I tried to re-execute the transaction. Will follow up later today with a confirmation.

**Comment by lxfind** [comment]
I think this is expected and is in fact a feature: the same owned object can only be used by one transaction at a time, since its version must be locked while the transaction is being executed. Only after one transaction finishes you can send another that uses the same object.
Our system prevents equivocation by detecting the same object is locked so you cannot send another transaction that uses it.
Could you provide context/background on what you are trying to achieve by sending two tx at the same time that uses the same owned object?

**Comment by MaithreyaSitaraman** [comment]
@gdanezis -- I am confirming that my previous statement was correct, that I again get the error when I tried to re-execute the transaction.

@lxfind -- my use case is as follows: A client may send me a thousand, (or one day, a million email addresses), and I need to create accounts and mint nfts for each person on their list. So, it makes sense to queue multiple transactions at the same time, and to be able to sign, store the txbytes somewhere, and execute them at a later time at my convenience.

**Comment by lxfind** [comment]
Ah cool thanks for the context!
OK there are two ways to achieve this:
1. You can make a thousand gas objects (by splitting a gas object into a list of amounts), and then use different gas object in each transaction, so that you can send them in parallel. The downside of this approach is then there may be a ton of dust gas objects, and is probably less efficient.
2. We will be adding and exposing Batch Transaction soon, where you will be able to send a thousand transactions in one batch, and only need one gas object, so that there is no concern of using the same gas object by multiple transactions.

It's expected that you would get an error even when you try to re-execute the second transaction, because the second transaction already contains the version number of the gas object, which was already locked and used by the first transaction.

**Comment by MaithreyaSitaraman** [comment]
@lxfind that makes sense, the batch transaction would be very helpful indeed. This is exactly what we need. If you could ping me here as soon as batch transactions are implemented that would be very helpful :).

**Comment by gdanezis** [comment]
Ok, it seems this is expected behaviour. Many thanks for the feedback about batching and pipe lining transactions. This is very useful to prioritize features.
