### ISSUE TITLE
[Gossip / Fullnode] Update last digest processed based on sequencing completion.

### ISSUE THREAD

**Issue by laura-makdah** [MystenLabs/sui#2535]

**Comment by mystenmark** [comment]
@gdanezis For full node sync, there are various points at which we can fail while trying to obtain a cert. However, the follower system marks batches complete (by updating the FollowerStore) as soon as they are received. Rather, we need to wait until all TXes in a batch have been locally sequenced before doing this, so that we don't skip TXes.
