### ISSUE TITLE
Refine use of certain terms to better match expectations

### ISSUE THREAD

**Issue by emmazzz** [MystenLabs/sui#2672]
Since Sui doesn't have a concept of "account" natively, it might make sense to consistently use "address" in docs and possibly other places to avoid confusion.

**Comment by Clay-Mysten** [comment]
Thanks so much, Emma! Let me take first run at fixing this.

**Comment by Clay-Mysten** [comment]
Hi @emmazzz , I am attaching a text file containing all of the references to all forms of "account" in docs.sui.io.
[account-refs.txt](https://github.com/MystenLabs/sui/files/8980545/account-refs.txt)

Please take a look and let me know if you have guidance for which references should remain. If not, I will use my own judgement and get plenty of review. Thanks!

**Comment by Clay-Mysten** [comment]
I am making this issue more general to also take on related work. In addition to:

1. the Use "address" instead of "account" in docs issue reported here
3. we're also addressing the claims Sam indicated needing toning down in the Learn section as reported in Discord here:
https://discord.com/channels/916379725201563759/955861929346355290/994891241324019752
See the attached "most" references as a starting point.
4. finally, I am trying to standardize on *net capitalization throughout the site in:
https://github.com/MystenLabs/sui/pull/3085
https://github.com/MystenLabs/sui/pull/3086
https://github.com/MystenLabs/sui/pull/3087
https://github.com/MystenLabs/sui/pull/3088
https://github.com/MystenLabs/sui/pull/3089
https://github.com/MystenLabs/sui/pull/3090
https://github.com/MystenLabs/sui/pull/3091
https://github.com/MystenLabs/sui/pull/3092

**Comment by Clay-Mysten** [comment]
[most-refs.txt](https://github.com/MystenLabs/sui/files/9074983/most-refs.txt)

**Comment by Clay-Mysten** [comment]
And "common" for "simple" too
[common-refs.txt](https://github.com/MystenLabs/sui/files/9075150/common-refs.txt)
.

**Comment by Clay-Mysten** [comment]
Reopening since we did not address the original request in #1, Use "address" instead of "account" in docs issue reported here

**Comment by Clay-Mysten** [comment]
Asking @randall-Mysten to help with the outlier in #1 above.

**Comment by Clay-Mysten** [comment]
Hi Emma,

I have finally gotten around to tackling the original account > address swap you requested in:
https://github.com/MystenLabs/sui/pull/4108

Please note, this change should get careful review so I don't unintentionally change the meaning of our docs. I've added numerous folks to the PR to help.

Finally, please note I left many seemingly relevant references to accounts in many pages, most notably:
https://docs.sui.io/build/devnet
https://docs.sui.io/build/devnet

This is required because we have output like this in our code:
`Owner: Account Address ( 9E9A9D406961E478AA80F4A6B2B167673F3DF8BA )`

So some concept of account exists. :-) That said, I reduced many references of "account address" to "address" per your recommendation. Please take a look. Thanks!
