### ISSUE TITLE
Assertions fail with tests that use shared objects

### ISSUE THREAD

**Issue by ncitron** [MystenLabs/sui#2751]
## Steps to Reproduce Issue
Run the tests included in [this](https://github.com/ncitron/sui-practice/blob/master/sources/share_bug.move) source file.

## Expected Result

The tests should fail due to the `assert!(1==0, 0)` statement.

## Actual Result

Test passes.

## System Information

* OS: MacOS 12.3.1
* Compiler: devnet branch

**Comment by damirka** [comment]
Hey @ncitron. I believe this bug is already fixed on main, so it's a matter of time since it gets to `devnet`.

Also you have 2 problems in your example:

1. `let thing = ...` - you have to use the value (or return it) of the variable since you're actually pulling a non-droppable struct.
2. To access the shared object you need to start a new transaction. Please see tests here (each action performed after `next_tx` call): [link to regulated coin tests](https://github.com/MystenLabs/sui/blob/main/sui_programmability/examples/regulated_coin/sources/regulated_coin.move#L333)

Closing this issue as it is fixed in main.
