### ISSUE TITLE
Transfer coin with one txn

### ISSUE THREAD

**Issue by gegaowp** [MystenLabs/sui#3287]
Today, transfers in wallet are done with 2 transactions, split or merge to have a coin with exact transfer balance and then do the actual transfer. With split_and_transfer we can make it one txn for small transfers but will not help for large transfer that needs merge.
The merge_and_transfer function is missing and thus this issue is blocked.

**Comment by nkavian** [comment]
I have this use case: If someone sends me 5 SUI, another person sends me 200 SUI, and then I plan to send 203 of those SUI to someone else; we need to be able to perform a `join_and_split_and_transfer`. The #3664 and #3289 is almost there if it supported an amount to transfer rather than the whole amount.

More broadly however, I'm also concerned what effect `merge_and_transfer` and `join_and_split_and_transfer` would have more broadly. It means all transactions now become single threaded since you can't have multiple callers at the same time. For example, a financial institution needs to be able to move multiple balances simultaneously to 3rd parties.
