### ISSUE TITLE
Implement `merge_and_transfer` txn

### ISSUE THREAD

**Issue by gegaowp** [MystenLabs/sui#3289]
this is blocking #3287 
more contexts can be found there.

**Comment by nkavian** [comment]
I have this use case: If someone sends me 5 SUI, another person sends me 200 SUI, and then I plan to send 203 of those SUI to someone else; we need to be able to perform a `join_and_split_and_transfer`. The #3664 is almost there if it supported an amount to transfer rather than the whole amount.

More broadly however, I'm also concerned what effect `merge_and_transfer` and `join_and_split_and_transfer` would have more broadly. It means all transactions now become single threaded since you can't have multiple callers at the same time. For example, a financial institution needs to be able to move multiple balances simultaneously to 3rd parties.

**Comment by gegaowp** [comment]
@nkavian sry for the late reply, this is a planned move, we have on-going work in coin.move and wallet.move to achieve the function you described, a related PR is https://github.com/MystenLabs/sui/pull/5018
I am closing this issue to de-dup for now

**Comment by nkavian** [comment]
I don't believe #5018 addresses my point, so closing this ticket doesn't help. If more PRs are created, I won't be able to track this externally and we'll have to start pinging your internal contacts our business team has.

That PR is heavily focused on massaging things with joins, divides, and splits. We have very little interest to manage and carve  coins into different buckets but it seems so much attention is being spent on that side.

Our focus is on wallet/transfer related requirements. We need the ability to submit to the platform multiple transfer requests for different amounts without having to serialize our requests. It would be great to see more conversation around wallet.move functionality that achieves this.
