### ISSUE TITLE
Cryptography interface to standardize address format

### ISSUE THREAD

**Issue by joyqvq** [MystenLabs/sui#3690]
It's a temp measure to unblock my progress with dapps. Ideally we'd want a cryptography interface, nacl won't be the only one it seems.

_Originally posted by @damirka in https://github.com/MystenLabs/sui/pull/3689#discussion_r934923336_

**Comment by damirka** [comment]
I would add a note here that since we now have a `flag` parameter in RPC and I assume we're going to support different cryptography, it makes sense to create an interface like "Signer" or something like that on the SDK side. The goal of this interface would be to provide a set of common cryptography functions:

- getFlag()
- getAddress()
- sign()

Currently I have them implemented as utils, but perhaps this should change.

**Comment by joyqvq** [comment]
https://github.com/MystenLabs/sui/blob/a0955c47974f73933edb832c664740502d19b55a/sdk/typescript/src/cryptography/ed25519-publickey.ts

https://github.com/MystenLabs/sui/blob/4baf554f12a3a43368429c2009bd6fd50adb830a/sdk/typescript/src/cryptography/keypair.ts

this is now provided in the sdk
