### ISSUE TITLE
build from source failed

### ISSUE THREAD

**Issue by wcw84** [MystenLabs/sui#3776]
Just followed https://docs.sui.io/build/fullnode#building-from-source, and met the error below:
> ~/sui# cargo run --release --bin sui-node -- --config-path fullnode.yaml
    Updating crates.io index
error: failed to select a version for the requirement `phf = "^0.11"`
candidate versions found which didn't match: 0.10.1, 0.10.0, 0.9.0, ...
location searched: crates.io index
required by package `workspace-hack v0.1.0 (/root/sui/crates/workspace-hack)`

OS: ubuntu 18

**Comment by FredYuuu** [comment]
save issue here

**Comment by satatocom** [comment]
Hey all,
If you did not install the Rust, please install it first from the following doc: 
https://docs.sui.io/build/install#rust
If you keep continue to get this error please reboot your OS. I experienced the similar issue and that's fixed my issue.
Sarp

**Comment by randall-Mysten** [comment]
Thanks for the heads up, we'll get this updated

**Comment by allansford2625** [comment]
I had same problem just now running ubuntu 18 on AWS M5.large instance. Fix below:
sudo apt remove rustc
curl --proto '=https' --t1sv1.2 -sSf https://sh.rustup.rs | sh
sudo apt-get update

then exited and reentered the powershell
it fixed the problem but then I got another problem.
turns out the cmake version needs to be greater than 12 to run parallel = 2
So did following to find out the version:
cmake --version
It was version 10+ so had to remove it and install the latest revision.

sudo apt remove cmake
git clone https://github.com/Kitware/Cmake/; cd CMake
./bootstrap && make && sudo make install

Finally one last problem: clang was not installed. Did the following:
sudo apt-get install clang

After that fired her up again and all went well.
Goodluck!

**Comment by Clay-Mysten** [comment]
> /cc @Clay-Mysten @randall-Mysten this is probably a call to have a very big banner pointing towards installing rust with [rustup](https://rustup.rs/).
> 
> Testing this on a docker container of a vanilla ubuntu may also be a good way to get quickly at perfectly reproducible instructions.

We already link from the fullnode doc to the Install > Prerequisites section where Rust is covered in detail as you describe here:
https://docs.sui.io/build/install#rust

Still, since this comes up regularly, I've added language emphasizing the need to keep packages updated and calling out Rust explicitly in:
https://github.com/MystenLabs/sui/pull/3879

All, please take a look. Thanks for the report and input!

**Comment by Clay-Mysten** [comment]
> I had same problem just now running ubuntu 18 on AWS M5.large instance. Fix below: sudo apt remove rustc curl --proto '=https' --t1sv1.2 -sSf https://sh.rustup.rs | sh sudo apt-get update
> 
> then exited and reentered the powershell it fixed the problem but then I got another problem. turns out the cmake version needs to be greater than 12 to run parallel = 2 So did following to find out the version: cmake --version It was version 10+ so had to remove it and install the latest revision.
> 
> sudo apt remove cmake git clone https://github.com/Kitware/Cmake/; cd CMake ./bootstrap && make && sudo make install
> 
> Finally one last problem: clang was not installed. Did the following: sudo apt-get install clang
> 
> After that fired her up again and all went well. Goodluck!

Thanks, @allansford2625. It sounds like you are running Linux. I would love your input on:
https://docs.sui.io/devnet/build/install#prerequisites

And whether we should try and cover update explicitly as we do install.

**Comment by Clay-Mysten** [comment]
Thankfully, @huitseeker also points to this user-generated doc:
https://github.com/kadrkn/Sui_Devnet_Update

I am asking if we should incorporate any of that into:
https://github.com/MystenLabs/sui/tree/main/docker/fullnode#readme

For instance this:
```
sed -i 's/stable/main/' docker-compose.yaml
```

I see `stable` here:
https://github.com/MystenLabs/sui/blob/main/docker/fullnode/docker-compose.yaml

I'm adding our fullnode experts for help.
