### ISSUE TITLE
CLI: publish binaries so that developers do not need to build them locally

### ISSUE THREAD

**Issue by 666lcz** [MystenLabs/sui#4298]
Building/upgrading the CLI can take a long time, let's publish pre-built binaries so that users can just download and use

**Comment by 666lcz** [comment]
@allan-bailey feel free to merge this issue if there's already another issue to track this

**Comment by Clay-Mysten** [comment]
When these land, please let me know so we can update the install docs. Thanks!

**Comment by 666lcz** [comment]
@ebmifa can we mark this as done given https://github.com/MystenLabs/sui/releases/tag/devnet-0.13.0 ?

**Comment by amnn** [comment]
Hey @ebmifa!  I was just looking into this because it came up during my oncall rotation.  As I understand it right now (from looking at our recent releases), we do have prebuilts but:

- Only for devnet, (`testnet-0.15.1` release didn't come with any).
- They include debug symbols.

Are the debug symbols here to stay?  They make the binaries quite large (1.1GB for `sui`) which limits their utility (long build vs long download).

**Comment by amnn** [comment]
Makes sense, thanks for clarifying!  This makes total sense for developers running validators and full nodes (and for us).  For developers who are using the sui CLI locally, we would likely want a stripped version of `sui` and maybe `sui-faucet` for a variety of platforms (eventually) as well.

**Comment by stefan-mysten** [comment]
We now have [releases with the Sui binary](https://github.com/MystenLabs/sui/releases), so closing this issue. https://github.com/MystenLabs/sui/releases
