### ISSUE TITLE
[coin management] generalize `TransferSui` to `PaySui`

### ISSUE THREAD

**Issue by sblackshear** [MystenLabs/sui#4761]
### Context

- The `TransferSui` transaction type allows you to pay directly with a single gas object (instead of using two coins)
- The newly added `Pay` transaction type allows you to pay multiple amounts, to multiple recipients, with multiple inputs
- The combination of these API's support most common payment scenarios. However, there is one requirement that is still hard to meet with a single transaction: transfer *all* of my coins elsewhere.

### Proposed solution

(Discussed with @Jordan-Mysten): generalize `TransferSui` to `PaySui` by allowing multiple recipients and multiple amounts:

```rust
pub struct PaySui {
    /// Non-gas input coins. May be empty
    pub coins: Vec<ObjectRef>,
    pub recipients: Vec<SuiAddress>,
    pub amounts: Vec<u64>,
}
```

This should (hopefully) be fairly easy to implement/test as a wrapper around the existing [`pay`](https://github.com/MystenLabs/sui/blob/main/crates/sui-core/src/execution_engine.rs#L304) function.

One conundrum is how to support the old `amount: Option<u64>` behavior in `TransferSui`. I think one good solution is:
- if `amounts` is empty, the total value of all input coins and the gas coin is divided equally among the `recipients` (and can tweak `Pay` to do this as-well
- if `amounts` is non-empty, it must be the same length as `recipients` and each recipient will receive the specified amount.

**Comment by gegaowp** [comment]
> transfer all of my coins elsewhere

presumably we will call PaySui with all user owned coins as `coins` and only one `recipient`. if we follow the impl of `Pay`, one tricky thing is that, one existing coin is needed before executing the txn for gas payment while all owned coins are deleted for the new merged coin.

`TransferSui` does not have this issue bc even if the whole coin is transferred, the input coin object still exists. a code [pointer](https://github.com/MystenLabs/sui/blob/48ff7c936e01950bd491a8d69ff8829b95613d83/crates/sui-sdk/src/transaction_builder.rs#L97). To get around this, one thing we can do is trying to reuse the input coins such that for this specific transfer all case, we can merge all coins into the first one for example and use that also as gas payment. any wisdom? @sblackshear 

One remaining edge case is, if we want to transfer all coins and evenly split them among N recipients, unless we can accurately determine the cost before execution, otherwise the recipient of the gas object coin will receive a different amount depending on the estimated cost vs actual cost, this might be okay if we assume the gas should be minimal here.

**Comment by sblackshear** [comment]
I did not understand the first problem you are mentioning. I think my confusion centers on the "merged coin" part of this:

> one existing coin is needed before executing the txn for gas payment while all owned coins are deleted for the new merged coin

`Pay` does not do any merging, which is why I am confused.

**Comment by sblackshear** [comment]
> One remaining edge case is, if we want to transfer all coins and evenly split them among N recipients, unless we can accurately determine the cost before execution, otherwise the recipient of the gas object coin will receive a different amount depending on the estimated cost vs actual cost, this might be okay if we assume the gas should be minimal here.

Good point. I think the gas cost will be statically knowable here (cc @oxade to make sure). If that's right, we can deduct the gas cost from the gas coin before calling `pay()`, and then everything will work as expected. But we have to take care to anticipate *all* of the gas costs (including object creation etc.)

**Comment by gegaowp** [comment]
> Pay does not do any merging, which is why I am confused.

Sry for the confusion. Today we construct tx with a gas object. Then we execute tx, in the case of "transferring all my coins" to one recipient, we delete all coins, create a coin with the total balance (this was the merging I meant but yeah it's not really a merge coin action) and transfer it to the recipient.

The problem I saw was, the newly created coin with all balance does not exist until tx execution so it cannot be used as the gas payment coin, which happens before tx exec. coins that belonged to the sender cannot either bc they are deleted after tx exec. 

Thus I was thinking one way to get around this is, instead of deleting existing coins and creating new coins, we can reuse the existing coins by redistributing the total balance, and creating an extra coin for residual balance if needed. As there is at least one owned coin and at least one recipient, it is guaranteed that we will always have a coin that exists before tx exec and still exists after tx exec, such that it can be used for gas payment.

@sblackshear does that make sense? Feels like it could have been easier with a PR, I will have a quick one for this 😆

**Comment by Jordan-Mysten** [comment]
@gegaowp My understanding is that with pay you can skip the step of combining all coins, and instead just pass a vector of all of your coins, letting the pay transaction take care of it.

**Comment by gegaowp** [comment]
@Jordan-Mysten yes, `Pay` transaction transforms `coins` based on `amounts`, and the issue I saw was about the gas payment in `PaySui`, as we want to pay gas with the input coins as we do in `TransferSui`, other than a separate coin as we do in `Pay`.

**Comment by Jordan-Mysten** [comment]
I imagined for a pay-based transferSui that we'd be able to pay gas with the same coin that we pay an address with

**Comment by gegaowp** [comment]
> pay-based transferSui

yes, I also wanted to implement transferSui/paySui as a wrapper of Pay, while the current pay impl approach afaict seems not working, I put up a quick draft PR with some comments to elaborate the idea https://github.com/MystenLabs/sui/pull/4803

sry for the confusion and hope this makes sense. @Jordan-Mysten @sblackshear

**Comment by lxfind** [comment]
A few thoughts:

So the primary motivation here for PaySui is to be able to transfer away all my SUI coins. But do we anticipate a case where we want to transfer away all my SUI coins AND transfer them to different recipients AND be able to divide coins equally? Asking because when Ge was explaining the semantics of PaySui to me, it took me 20 mins before I could understand all the different ways of what it could do. I think clients/apps will have a hard time digesting how to use PaySui. The dependency on gas_budget is also going to be tricky: unless we just hardcode a gas cost for PaySui, there is no guarantee that the budget would be accurate. The algorithm seems so dynamic that there would be no way to predict gas cost around various object creation/deletion cases, not mentioning that gas price could in practice be dynamic which could impact SUI cost as well.

My recommendation is that we just generalize TransferSUI to support a list of extra SUI coins, but keep everything else the same: one sender, and optional amount (None indicating transfer all). This allows us to handle the case we want: be able to transfer away all my SUI coins in a guaranteed way. And if we discover more complex popular use cases latter, we could optimize accordingly.

**Comment by lxfind** [comment]
Furthermore, I remember that has been asks about supporting a list of gas coins, instead of just one.
If we support that, then we don't even need a new transaction type. TransferSui could just transfer away all SUI coins by specifying all coins as gas objects and leave amount empty.

**Comment by gegaowp** [comment]
>  supporting a list of gas coins

yes I proposed this one, the motivation back then was to solve the problem when ppl have dusts of Sui coins. A related q is that, following the idea, do we want to split the gas cost evenly to all recipients?

**Comment by lxfind** [comment]
The idea here, imho, is that if we want to pay gas using the input coins, we should keep it simple and have only 1 recipient

**Comment by sblackshear** [comment]
I agree with the desire to make the gas behavior of PaySui simpler.

I do suspect that there's a use-case for paying multiple recipients in SUI where some part of the payment comes out of the gas coin (or, to put it differently, where the caller doesn't have to worry about which coins are used for payment vs gas). But sticking with the simpler version of transfer SUI to start + worrying about this if/when it becomes a problem seems reasonable.

**Comment by sblackshear** [comment]
On multiple gas coins: my instinct here is that this introduces complexity that is not well motivated at this time (but I might very well be wrong!). Here's something I wrote previously

- My intuition is that the answer to (1) will be "pretty small" (<= $0.10 for most tx types if we want to be competitive with other platforms)
- My intuition is that the answer to (2) will be "pretty big", since an average address will likely get a coin by buying a bunch of SUI from a marketplace, receiving a chunk of SUI from staking rewards, or receiving a payment of some form (P2P, NFT sale, NFT royalties, ...). "Pretty big" is vague, but I think most of these coin values are more likely be in the ballpark of $10s-100s of dollars.
- If we expect (2) >> (1), then I think we should also expect the use-case of paying for a single tx with multiple gas coins to be pretty uncommon (since an average single coin will be more than big enough). It seems unfortunate to ask wallets, clients, explorers, etc. to deal with this edge case if so.

**Comment by lxfind** [comment]
> I do suspect that there's a use-case for paying multiple recipients in SUI where some part of the payment comes out of the gas coin

I agree. Introducing multiple recipient is not too bad, just that we need to define the semantics clearly.
The way I think about implementation complexity vs expressiveness in Sui is to look at it through 4 layers:

Native Transaction -> Move Transaction -> Batch Transaction -> Multiple Transaction

The Native Transaction should be the most lean layer and we should avoid adding things to it unless we absolutely cannot do in other layers (or the cost of doing it in other layers is significantly higher).
Move Transaction is an ideal layer because it's most convenient to develop.
Down the line we could support the ability of using output objects of previous sub-transaction within a Batch Transaction, so that Batch Transaction can become much more powerful and expressive, and could potentially handle the case of sending sui to multiple recipients and etc.
Then there is the application layer (e.g. wallet) that can always send multiple transactions to achieve something complex.

**Comment by gegaowp** [comment]
> a use-case for paying multiple recipients in SUI where some part of the payment comes out of the gas coin

agreed, we can still do so as long as we separate the implementation for these 2
- "paying multiple recipients in SUI where some part of the payment comes out of the gas coin",  and where the amounts are specified, indicating the residual value under sender can still pay for the gas cost, maybe we can call this paySui
- paying all coins to **one** recipient, where the amount is not specified, maybe we can this payAllSui

Implementation wise, I will implement separately for paySui and PayAllSui to avoid make pay more complex, but will try to minimize duplicate codes when possible. what do you folks think?

**Comment by lxfind** [comment]
> "paying multiple recipients in SUI where some part of the payment comes out of the gas coin", and where the amounts are specified, indicating the residual value under sender can still pay for the gas cost, maybe we can call this paySui

How is this different from the current proposal for PaySui? Once you specify amounts, and still want to drain all your SUI coins, you end up with the same problems.

**Comment by gegaowp** [comment]
> How is this different from the current proposal for PaySui?

the main difference is that, the current proposed paySui was originally intended to cover the "transfer all with multiple recipients" case as well, thus gas_budget / estimated_gas_cost has to be taken into consideration to decide amounts for each recipient, it was not possible to strictly split evenly bc neither gas_budget nor estimated_gas_cost is accurate.

if we forget about the transfer all case of paySui, then what we can do is something like
- create new coins under recipients per the specified amounts
- put all residual SUI balance after deducting amounts into the first input coin, meanwhile deleting all other input coins
- pay gas with the first input coin, if the residual SUI balance is indeed enough to pay for gas, all good; otherwise, the transaction would fail with InsufficientGas error.

**Comment by gegaowp** [comment]
yeah this is very fair question:
- one case is when ppl only have one coin and wants to transfer to multiple recipients;
- another is related to coin selection, with coin_selection APIs we provide, ppl can get a selected coin as a gas payment object, but they might want to use only certain coins for this transfer txn, while keeping others untouched, for example to reserve other coins for parallel txns.

Agreed that these are likely corner cases and I will start with the PayAllSui as well.

**Comment by lxfind** [comment]
Cool. I think as starter, we could be a bit more flexible than PayAllSui.
Essentially we can generalize TransferSui, maybe call it PaySui, where we can support multiple coins in the input.

**Comment by gegaowp** [comment]
Iirc to replace TransferSui with more general version, I think we will have to separate the semantic meaning of TransferSui to paySui and payAllSui, did I miss sth about the generalization you meant?
Agreed that for all new functions I am going to implement, they should all take a vector of coins rather than one input coin.

**Comment by lxfind** [comment]
TransferSui supports two modes: transfer a specific amount, or transfer all. But it only accepts one input coin today.
I was suggesting that we extend TransferSui to support a vector of input coins, and keep both intents: transfer a specific amount, or transfer all.

**Comment by lxfind** [comment]
> in a "transfer" flow, user can add pairs of <recipient, amount>, this can all be handled by PaySui

I don't fully understand this flow. In this case, which coin will be paying gas? And why not use a Batch transaction for this case?

**Comment by gegaowp** [comment]
It will be the first coin among coins selected by a separate "coin selection" for this whole transaction.
Re batch transaction, iiuc before batch transaction can pass / share objects among sub-txns, we want to provide a way to send to multiple recipients with the same set of input coins in one txn, instead of a sequence of transactions to do so, right?

if we want to have 2 new native transaction types to handle payment around Sui, I was proposing that PaySui + PayAllSui is cleaner than PaySui + generalized TransferSui.

However if we feel PaySui is not necessary, then it makes sense to generalize the TransferSui to take in a vector of coins.

**Comment by lxfind** [comment]
All makes sense! Thanks for explaining.
If there ends up a lot of shared code between PaySui and PayAllSui, I think it's reasonable to combine them into one, just maybe make the recipient field of the tx an enum of two independent cases.
