### ISSUE TITLE
move reading active validators to RPC / SDK. 

### ISSUE THREAD

**Issue by gegaowp** [MystenLabs/sui#4826]
now we have this logic in Coin.ts, we should expose this in RPC / SDK instead
https://github.com/MystenLabs/sui/blob/2fdc7ed9bd27a6d4bc2e807dcfb2a9ed712a5da2/apps/wallet/src/ui/app/redux/slices/sui-objects/Coin.ts#L225

**Comment by sblackshear** [comment]
I interpreted the TG question as asking about reading historical validator sets in addition to the current one. That won't be possible yet because we don't yet support reconfiguration, but perhaps we can do this via emitting an event with the new validator set each time we reconfigure (cc @emmazzz).

Aside: Coin.ts seems like it might not be the most logic home for this API...

**Comment by gegaowp** [comment]
@sblackshear oh, thanks sry I misunderstood that. Yes the Coin.ts was a quick hack to unblock Stake feature. naively I think we still want some endpoints in SDK / RPC to fetch active validators
