### ISSUE TITLE
Sui Move Library docs out-of-date

### ISSUE THREAD

**Issue by amnn** [MystenLabs/sui#5905]
After launching Dynamic Fields, the documentation in [Use Sui Move Library](https://docs.sui.io/build/move/sui-move-library) is now out-of-date (it mentions `transfer_to_object` etc which have now been replaced with the APIs documented [here](https://docs.sui.io/build/programming-with-objects/ch5-dynamic-fields)).  We should update this, and do a general sweep of the docs for references to the old APIs in `transfer`.

**Comment by randall-Mysten** [comment]
In an ideal world, we would meet well before releasing new functionality and identify acceptable and reasonable time frames for the work required to update docs. This would allow us to find all of the instances that need to be updated and publish all changes with the feature release. We can't plan for and schedule unknowns, so everything becomes and urgent reaction to an update to the code instead of a thoughtful and quality release.
