### ISSUE TITLE
Gas consumption of function calling is too high

### ISSUE THREAD

**Issue by nikolai-aftermath** [MystenLabs/sui#6343]
I found that the gas consumption of function calling (namely, `Call` and `Ret` instructions in MoveVM) is too high. This is especially evident when performing a number of simple mathematical functions which should be as "zero cost" as possible, e.g. abstracting over signed and/or fixed-point numbers.

Here [AftermathFinance/sui-move-inline](https://github.com/AftermathFinance/sui-move-inline) I'm doing a simple test that shows that not inlined version of numbers addition can consume about 20 times more gas than inlined.

test1 total gas fee: 0.000002451 SUI (2451 MIST)
test2 total gas fee: 0.000043475 SUI (43475 MIST)

**Comment by sblackshear** [comment]
Move calls are expensive relative to other instructions because they do a lot of [allocation](https://github.com/move-language/move/blob/main/language/move-vm/runtime/src/interpreter.rs#L160)--we need to allocate a new stack frame with its own arguments, type arguments, pc and a reference to the function being called, move each of the arguments from the operand stack into the frame, etc.

I think the right fix for us here is to support `#inline` hints at the compiler level to eliminate the overhead of these conceptually "zero-cost" abstractions. This is something the Move core contributors have been talking about recently, and is perhaps time to prioritize (cc @tnowacki who had thoughts on this).

**Comment by sblackshear** [comment]
Note also that we are working on moving to a "flat" gas fee for computation, so the effects of these sorts of optimizations should only be visible if they actually make a measurable difference in the transaction execution time. I expect they will not in this case, but would be interesting to try.
