### ISSUE TITLE
Availability Of Event Data on Fullnodes?

### ISSUE THREAD

**Issue by PaulFidika** [MystenLabs/sui#6789]
If you create a data-object, and then store it (send it to someone), versus creating a data object and then broadcasting it, the event-broadcast method costs much less gas. It appears that the gas-cost for event-data is nearly constant, while the gas-cost for stored-data increases linearly with size.

Is event data guaranteed to be available at all Fullnodes forever? Or is it considered prunable historic data, like old transaction history, that can be dropped from fullnodes and left to some sort of archival node?

I'm considering where to store on-chain metadata (data that will only be consumed by off-chain processes), and one way is to store it in an object, while another is to broadcast it as an event. (Since event-data cannot be edited, the module would have to rebroadcast its metadata every time it wants to change something.) The event-method is much cheaper, but I'm afraid that the metadata may become less available at fullnodes in the future, compared to "live" objects which will always be available. Also it may simply be more convenient for off-chain processes to fetch live-object data over event-data.

Thoughts?

Also worth considering: if event-data is kept in memory by fullnodes forever, but is not included as part of the storage staking deposit, it may be possible to attack the network by broadcasting events with large amounts of data millions of times, which is inexpensive to do since the gas-cost is near constant, but fullnodes are required to store, hence wasting the space available on Sui. I would think that the cost of broadcasting 1 KB of event-data should == freezing 1 KB of object-data.

**Comment by sblackshear** [comment]
> Is event data guaranteed to be available at all Fullnodes forever? Or is it considered prunable historic data, like old transaction history, that can be dropped from fullnodes and left to some sort of archival node?

The latter--events prunable historic data. You will be able to get old events from archival nodes or third-party indexers, but full nodes will get rid of them periodically.

Thus, whether it makes sense to use events vs objects really depends on the use-case--if your app will always load the data, you want an object, but events are useful for transient data like "hottest tweets", "latest scores", etc.

**Comment by gegaowp** [comment]
^^ what Sam said above.

Besides even the archival nodes might not have all old events, what archival nodes will have for sure are some snapshots of all objects at certain timestamp, and all transactions from genesis in batches.
If old events are needed but not available on FN, one way to retrieve them is to fetch snapshots and txns around the desired events, replay the txns until the desired events are generated.  Obviously this is a very expensive action and requires a FN to replay the txns, so it should mostly be used for massive event backfill rather than ad-hoc event request.

I am building libraries for indexer, one planned feature is indexer p2p sync, meaning that among the indexer network, if one indexer has certain old event data, other indexers can get them via p2p sync and avoid txns replay on FN.

Indexer can have custom pruning strategy but looking at our target TPS, it is not sustainable to keep all events forever even on indexer (which can do sharding etc. more easily compared with FN), old events prob will be stored in cold storage like S3 files in the long run.

**Comment by PaulFidika** [comment]
Okay thanks for the answers! I think it makes sense to have metadata stored on-chain as an object then.

For events, is there any rule for how long they'll be kept around on fullnodes for? Like a few weeks perhaps?
