### ISSUE TITLE
confirm link checker action is set up correctly

### ISSUE THREAD

**Issue by georgescharlesbrain** [MystenLabs/sui#7031]
Found a dead link in the docs, mentioned in issue #7030.
After doing some research, I've seen that there should be a [github action](https://github.com/lycheeverse/lychee-action) running looking for dead links in the docs.

Settings file for the link checking action can be found [here](https://github.com/MystenLabs/sui/blob/main/.github/workflows/links_checker.yml).
Not sure when this GitHub action is run and where it writes the output, but this dead link should have been caught.

**Comment by georgescharlesbrain** [comment]
It seems it has been 2 months since the link checker ran.
https://github.com/MystenLabs/sui/actions/workflows/links_checker.yml

**Comment by mlegner** [comment]
@randall-Mysten @ronny-mysten There still seems to be an issue with the [Links Checker action](https://github.com/MystenLabs/sui/actions/workflows/links_checker.yml) (since 9 months). For some reason I don't understand, the schedule does not actually trigger the workflow.

There seems to be another issue with the `micalevisk/last-issue-action`: I just triggered the workflow manually (see [here](https://github.com/MystenLabs/sui/actions/runs/5532396076)) and it failed to create/update a report issue.
