### ISSUE TITLE
[docs] ObjectID and Address are same in implementation but documented differently

### ISSUE THREAD

**Issue by FrankC01** [MystenLabs/sui#7345]
From [docs](https://docs.sui.io/reference/sui-json#type-coercion-rules)

Address | 20 byte hex string prefixed with 0x | "0x2B1A39A1514E1D8A7CE45919CFEB4FEE70B4E011" | 0x2B1A39: string too short2B1A39A1514E1D8A7CE45919CFEB4FEE70B4E011: missing 0x prefix0xG2B1A39A1514E1D8A7CE45919CFEB4FEE70B4E01: invalid hex char G
-- | -- | -- | --
ObjectID | 16 byte hex string prefixed with 0x | "0x2B1A39A1514E1D8A7CE45919CFEB4FEE" | Similar to above

But all objects and addresses are the same as far as digits byte count. Examples:
```bash
0x97b74ba62590617e8d263ae1200b0c109f42a167    <- Address (20 byte hex string)
0x764d5eb597991c3de278e5102a8d454e6e526e85 <- Gas object 20 byte hex string
0x0e270804cda8d26fe5f28fb3ff2e0ef887786df8      <- Data object 20 byte hex string
```

**Comment by randall-Mysten** [comment]
Hi @FrankC01 - There's the difference of 20 byte v 16 byte. Yes, all of the values are the same byte count. I am not sure what the concern or issue is. Could you add more detail?

**Comment by FrankC01** [comment]
Just curious if the documentation is wrong because both string lengths (42) and byte count (20) are the same.

**Comment by randall-Mysten** [comment]
@amnn Any additional detail you can add here?

**Comment by amnn** [comment]
I think @FrankC01 is right and the docs are stale here -- ObjectID has not been 16 bytes for some time (I think the change to 20 bytes even predates me joining the company!)  Thanks for spotting @FrankC01.

It's still worth distinguishing them as different types because they don't share the same namespace (i.e. the same 20 bytes could point to an address or a completely unrelated object when interpreted as an Address or ObjectID respectively), but @randall-Mysten, can we update the docs so that ObjectID is 20 bytes?

**Comment by FrankC01** [comment]
@amnn 

Yes, fully realize that they are certainly different of what they refer to on SUI. Just noted the doc `nit`

fastfrank

**Comment by amnn** [comment]
This looks to be fixed in the docs now, so I'll close the issue!
