### ISSUE TITLE
Poison pill TX can cause infinite crash loop

### ISSUE THREAD

**Issue by mystenmark** [MystenLabs/sui#7408]
In devnet, we encountered a poison-pill tx, which caused validators to panic.

The retry log worked as designed, and gave up after 3 retries:

```
2023-01-14T18:16:04.111982271Z stderr F 2023-01-14T18:16:04.111940Z ERROR sui_core::authority: Abandoning in-progress TX after 3 retries.
```

However, the execution driver continued attempting to execute the cert:

```
2023-01-14T18:16:04.112126242Z stderr F 2023-01-14T18:16:04.112077Z DEBUG sui_core::execution_driver: Pending certificate execution activated. digest=7jqRiFm5XoFhRHwPKQwyeaYESwYJsfWdXpqYfwBkGGFw
```

We need to make sure this can't happen. Possible solutions:
- Probably the easiest method: Maintain a permanent record of txns that have exceeded the retry count, and check that in execution driver. We should also guard against automated resubmission of the tx. Lastly, we'll need a tool to remove the poison tx from this list once we have patched the bug. 
- Alternative: Add crash detection to execution driver. We can't use drop handlers becuase we use `panic = abort`, but we could have execution driver mark txns as in progress, and then mark them as finished when they either succeed or fail - any tx that is marked in progress when we load it from the table was in progress during a crash. However it doesn't follow that it was the tx that caused the crash.

**Comment by lxfind** [comment]
> Lastly, we'll need a tool to remove the poison tx from this list once we have patched the bug.

We can keep the list of poison tx in the per-epoch store, they would be dropped naturally when we upgrade the software at epoch boundary. At epoch boundary, we also check against the list to make sure we don't wait for them before closing the epoch.
In the case the bug is not fixed, they will just be retried again in the next epoch if someone sent them again.

**Comment by mwtian** [comment]
I think validators need to retry a transaction unless it is absolutely certain that other validators will not attempt or succeed executing the transaction, to avoid state divergence. Two possibilities,
1. After restart, pending transactions need to be executed sequentially or in a binary search pattern until the poison transactions are identified and other transactions are committed, before a validator can start accepting new transactions.
2. If possible, use panic = unwind and mark panicked transactions, assuming it helps the majority of cases. I'm not sure if this would work though.

Honestly, avoiding retrying transactions that crash validators feels a bit late in the game. If someone intentional is behind, it seems trivial to craft "poinson" tx with different digests. Pushing an emergency patch for the crash seems necessary in most scenarios.

**Comment by lxfind** [comment]
The problem is how would we push the emergency patch. An emergency patch will certainly need to go with a software update, which must happen at epoch boundary (otherwise we risk of fork if a software update happens within the middle of epoch). But epoch cannot end if there are pending certificates that could not be executed. So we need a way for validators to agree that a certain transaction needs to be excluded from the epoch (maybe through consensus?)

**Comment by mystenmark** [comment]
I think we can keep this simple:

- Let's not worry about a tx that crashes some validators but not others.
- Under that assumption a poison pill cannot make it into a checkpoint, but @lxfind makes a good point that this would prevent the epoch from ending.
- But, every validator can make its own decision about whether a tx is bad or not and if they all agree, consensus is not required.
- We are already 90% of the way there in terms of detecting a poison pill.

If we want to worry about crashes that only hit some validators, then we may abe in trouble. But that can also be dealt with by having the crashing validators upgrade (or downgrade) to the version that is not crashing.

**Comment by lxfind** [comment]
I agree that we probably don't need to worry about consensus if there is a crash/panic. But what about execution returns Error?

**Comment by mwtian** [comment]
Re emergency patches, I think they need to be backward compatible in all aspects so reloading with the patch would fix the issue and continue in the same epoch. I still think they could be necessary, if there are non-crash issues discovered e.g. data corruption triggers or security vulnerabilities.

Also this discussion reminds me about a possible simplification: Sui should not need to store user transactions into the transaction recovery log or pending_certificates table. Checkpoint executions should guarantee transactions included in checkpoints get eventually executed. System transactions (from Narwhal) may still need a redo log. "Transaction of death" would get dropped after restarts.

But this would not identify and prevent the transaction from client retries. I think retry count incremented for all inflight transaction at crash is a bit too coarse and will hurt unrelated transactions / users. Another idea is to put logic to detect crashes and drop transaction in quorum driver. This should be simpler to implement, and similarly (in)effective against malicious actors compared to validator side detections.

For execution returning errors, the current thinking is that "it should not happen". The hope is that if it happens, it should be predictable. Maybe we can treat cert execution error as crashes ..

**Comment by lxfind** [comment]
> Re emergency patches, I think they need to be backward compatible in all aspects so reloading with the patch would fix the issue and continue in the same epoch.

That's a very difficult assumption to always satisfy, though.

**Comment by mystenmark** [comment]
> I think retry count incremented for all inflight transaction at crash is a bit too coarse and will hurt unrelated transactions / users. Another idea is to put logic to detect crashes and drop transaction in quorum driver

We don't track retry count for all inflight transactions. We only start tracking it once a tx is recovered from the recovery log / wal.

Quorum driver is not a good place to do this because it can't distinguish a crash from a network timeout, and we need opposite behavior in those two cases (don't retry a crash, do retry a network timeout).

I will put up an initial PR for this this week, I think this won't require huge changes for something that can at least prevent a crash loop.

**Comment by mwtian** [comment]
Identifying crash should be possible by keeping track of per-server generations in QD. Server would reject a request if it is for the wrong generation, and QD would detect a tx of death if servers with 2f+1 stakes have incremented their generations. But I agree detecting tx of death in validators could be better. I think alerting on and identifying the tx causing crashes would be important for fixing the issue quickly, and this helps building the filtering logic too.
