### ISSUE TITLE
[rpc] Fix dynamic fields pagination

### ISSUE THREAD

**Issue by 666lcz** [MystenLabs/sui#7686]
There's likely a pagination bug in the [fullnode code](https://github.com/MystenLabs/sui/blob/main/crates/sui-sdk/src/apis.rs#L69). This can be reproduced indeterministically by running e2e tests

```
[1]  FAIL  test/e2e/dynamic-fields.test.ts > Dynamic Fields Reading API > go to next cursor
[1] AssertionError: expected +0 to be above +0
[1]  ❯ test/e2e/dynamic-fields.test.ts:64:43
[1]      62|         null
[1]      63|       );
[1]      64|       expect(dynamic_fields2.data.length).greaterThan(0);
[1]        |                                           ^
[1]      65|       expect(dynamic_fields.nextCursor).not.toEqual(null);
[1]      66|     });

```

**Comment by losman0s** [comment]
Can this cause duplicates when iterating through the pages? Multiple devs seem affected by that.

**Comment by samlaf** [comment]
This bug has been annoying me for quite a well, so I decided to spend a bit of time researching into it.
My use case is that I'm trying to retrieve the Bayswap pools from https://suiscan.xyz/testnet/object/0x397b92bf1b173f14077afeca3f93243fe19718d3a791bbb433e47d0a96775c2f. This object contains a bag which contains the pool ids as dynamic fields. There are at the moment 540 such pools, but querying them via the cli client or ts sdk only results in 379 pools, most likely due to this duplicate problem and weird cursor behavior.

Here's the example code I've been using to test this behavior:

```typescript
import { JsonRpcProvider, testnetConnection } from '@mysten/sui.js';

async function main() {

    const provider = new JsonRpcProvider(testnetConnection);

    // https://suiscan.xyz/testnet/object/0x397b92bf1b173f14077afeca3f93243fe19718d3a791bbb433e47d0a96775c2f
    // this globalStorage contains a bag which contains all the bayswap pools as dynamic fields
    const ownedObjs = await provider.getObject({
        id: "0x397b92bf1b173f14077afeca3f93243fe19718d3a791bbb433e47d0a96775c2f",
        options: {
            showContent: true
        }
    })
    const numPools = (ownedObjs.data?.content as any).fields.pools.fields.size
    console.log(`Bag contains ${numPools} pools as dynamic fields`)
    console.log("Retrieving them 50 at a time... (bug causes duplicates)\n")

    const poolIdsSet = new Set();
    let lastSetSize = poolIdsSet.size
    let cursor = undefined;
    let hasNextPage = true;
    let totalRetrieved = 0
    let res
    while (hasNextPage) {
        res = await provider.getDynamicFields({
            parentId: "0xfa09625201f191a882f5d1fba2760e7b7f657f7aa06a71b885dd6640dfb897ba",
            cursor,
            limit: 50
        })
        const poolIds = res.data.map((pool: any) => pool.objectId)
        poolIds.forEach((poolId: string) => poolIdsSet.add(poolId))
        totalRetrieved += res.data.length
        console.log(`${poolIdsSet.size - lastSetSize}/${res.data.length} retrieved pools were new (non-duplicates))=. Total non-dups = ${poolIdsSet.size}. Total queried: ${totalRetrieved}`)
        lastSetSize = poolIdsSet.size
        cursor = res.nextCursor
        hasNextPage = res.hasNextPage
    }
    console.log(`\nRetrieved ${poolIdsSet.size} / ${numPools}`)

}

main()
```

and the output:

```
Bag contains 540 pools as dynamic fields
Retrieving them 50 at a time... (bug causes duplicates)

50/50 retrieved pools were new (non-duplicates))=. Total non-dups = 50. Total queried: 50
50/50 retrieved pools were new (non-duplicates))=. Total non-dups = 100. Total queried: 100
19/50 retrieved pools were new (non-duplicates))=. Total non-dups = 119. Total queried: 150
50/50 retrieved pools were new (non-duplicates))=. Total non-dups = 169. Total queried: 200
48/50 retrieved pools were new (non-duplicates))=. Total non-dups = 217. Total queried: 250
9/50 retrieved pools were new (non-duplicates))=. Total non-dups = 226. Total queried: 300
0/50 retrieved pools were new (non-duplicates))=. Total non-dups = 226. Total queried: 350
50/50 retrieved pools were new (non-duplicates))=. Total non-dups = 276. Total queried: 400
50/50 retrieved pools were new (non-duplicates))=. Total non-dups = 326. Total queried: 450
9/50 retrieved pools were new (non-duplicates))=. Total non-dups = 335. Total queried: 500
12/50 retrieved pools were new (non-duplicates))=. Total non-dups = 347. Total queried: 550
22/50 retrieved pools were new (non-duplicates))=. Total non-dups = 369. Total queried: 600
0/50 retrieved pools were new (non-duplicates))=. Total non-dups = 369. Total queried: 650
0/50 retrieved pools were new (non-duplicates))=. Total non-dups = 369. Total queried: 700
10/20 retrieved pools were new (non-duplicates))=. Total non-dups = 379. Total queried: 720

Retrieved 379 / 540
```

Looking at the code, it seems like the `suix_getDynamicFields` json-rpc call runs this [code](https://github.com/MystenLabs/sui/blob/cdd4607a546c00aa937302ec06819d28be36cb45/crates/sui-json-rpc/src/indexer_api.rs#L251) which eventually calls the storage's [get_dynamic_fields_iterator](https://github.com/MystenLabs/sui/blob/cdd4607a546c00aa937302ec06819d28be36cb45/crates/sui-storage/src/indexes.rs#L1086) function, which I am guessing is where the bug lies (might also actually in the code that writes to the dynamic_field_index). I could try to help debugging this further and hopefully fixing it if someone could give me more intuition as to what might be going wrong.

Thanks :)

**Comment by healthydeve** [comment]
How are you checking for duplicate pools? Are the object IDs different for the pools here? This bug actually got fixed a while back I think.

**Comment by samlaf** [comment]
> How are you checking for duplicate pools? Are the object IDs different for the pools here? This bug actually got fixed a while back I think.

I am checking for object IDs yes. I was assuming the Bag would force its items to have unique IDs, but you're now making me have second doubts. Here's a pool example: https://explorer.sui.io/object/0x2c9bb69da983fa4e242e8d7b2de1261475fa82b766893e3381b776c528e94885

Anyways even if somehow pool ids could get overwritten and hence the duplicates were normal (which I doubt), the fact that we are querying 720 different items while there are only 540 items in the pool is clearly a bug.

**Comment by healthydeve** [comment]
Duplicate ObjectIds should not be normal, can you show me an example that has a duplicate object Id? I just tried to paginated for the pool example you just gave, and I did not find a duplicate in the API.

**Comment by samlaf** [comment]
Have you tried running my code snippet above? I could have gotten you the duplicate object ids if it was still behaving like what I posted yesterday, but I'm guessing there was an update to the code in the past few hours. Now it's returning
![image](https://user-images.githubusercontent.com/9342524/235603345-f89e51d4-0047-4df5-9925-43a9e3bdb091.png)
so no duplicates but only returns 52 out of the now 557 pools... something's clearly wrong.

**Comment by josemvcerqueira** [comment]
I have faced the same issue.

The pagination logic is broken. On Interest Protocol we have a Bag with a size of 121 fields. 

The id of the object on the testnet is 0x0b7fe6779f5aa718a47279399a37a3a2f3239b69879518d6d51b592834d5aa56

https://explorer.sui.io/object/0x0b7fe6779f5aa718a47279399a37a3a2f3239b69879518d6d51b592834d5aa56?network=testnet

When I use the TS SDK getDynamicFields, it is impossible to get all fields. The method never returns hasNextPage and only returns 17 unique items.

I have written a small script to showcase the issue at:

https://github.com/josemvcerqueira/get-dynamic-bug

After installing the dependencies with 

```bash
  npm i
```

You can run the script with 

```bash
  npm run dev
```

**Comment by healthydeve** [comment]
The pagination can return something different everyday because people can add objects to the pool. We are in the middle of investigating what the database actually looks like and should have some results for this bug by next week. This bug is not actually related to pagination as the iterator seems correct, we are looking into whether or not its related to the writes to our DB.

**Comment by oxade** [comment]
Issue fixed in https://github.com/MystenLabs/sui/pull/11789
