### ISSUE TITLE
Programmable Txs without enforcing input usage

### ISSUE THREAD

**Issue by kchalkias** [MystenLabs/sui#8776]
Useful for registering a memo in the blockchain (retrievable from archival node)

**Comment by fum-is-chum** [comment]
Hey @kchalkias, is there any code example on how to use the inputs of the transaction block as a memo or note? Thanks!

**Comment by fum-is-chum** [comment]
Hey @kchalkias @tnowacki I've tried this feature to send memo in a transaction
https://suivision.xyz/txblock/Aj9Q49XTgAZgcSe97fD1oSrw4wVzwPFKK539PNd29scD

Current behavior is the string will be parsed as array of decimal
![image](https://github.com/MystenLabs/sui/assets/34566225/dcca7b07-040c-4911-9f7f-d49456b99162)

I've done some experiments and in order to parse the string as string, we need to use the input inside a movecall like this one
https://testnet.suivision.xyz/txblock/HAjFNx3rxGWdkBcSdFZM5oKgNwYroP7WTW2Dz35TYbMh
![image](https://github.com/MystenLabs/sui/assets/34566225/8d66f574-492f-42f6-b303-6479587d9799)

Is there any way to do this without using movecall?

**Comment by tnowacki** [comment]
Are you using suivision to build your transactions? If so, it might be an issue on their end?

As far as the network is concerned, pure (non-object) arguments get passed in as an array of bytes. Those bytes are then deserialized via BCS to the specified Move value (depending on what command is used). Or they are left alone as bytes if never used.

**Comment by fum-is-chum** [comment]
Yeah, what I am trying to say is, is there any way to deserialized the input into string without using it into a movecall arguments?

**Comment by tnowacki** [comment]
> is there any way to deserialized the input into string without using it into a movecall arguments

There is not, but what is your usage for that case?

**Comment by fum-is-chum** [comment]
Just trying to provide a UI tool to allow user to send transaction with memo, and it will be great if there is a standardized way to do it

**Comment by tnowacki** [comment]
They can just send the bytes for the memo. No issue there.

If they want to enforce it to be a utf8 string, they can call `std::string::utf8`. I don't see the benefit of adding a way to enforce its a utf8 string without just calling the function that does so.
