### ISSUE TITLE
[narwhal] Do not deserialize pubKeys when used as identifiers

### ISSUE THREAD

**Issue by kchalkias** [MystenLabs/sui#8930]
Narwhal uses pubKeys as identifiers but we should ensure we're only using its bytes and not deserializing to points. WIP
Generally ensure, we don't overdeserialize pubkeys

**Comment by jonas-lj** [comment]
I've looked a bit into this and `PublicKey`s are indeed used as map keys in a few places. However, all deserialization of public keys (calls to `PublicKey::from_bytes`*) are going through `NarwhalConfiguration::get_public_key` which is only called by the `new_epoch` and `new_network_info` methods where the given validators' public keys are parsed from a `NewEpochRequest` and `NewNetworkInfoRequest`. So while using public keys as keys in these maps may be a bit overkill, I don't think there's any over-deserialization going on, and the public keys are, when used as keys in a map, just used in their cached serialized form because the `Hash` and `PartialEq` implementations for `PublicKey` just considers the keys' byte representation.

* I've also checked for indirect calls to deserialize that could include a public key, but couldn't find any.
