### ISSUE TITLE
[feature-request][ts-sdk] Add back the Provider interface

### ISSUE THREAD

**Issue by JackyDisc** [MystenLabs/sui#9795]
## Description

Add back the `Provider` interface implemented by `JsonRpcProvider`.

### Rationale

It's common for the application to add some custom logic that wraps `JsonRpcProvider`, e.g. Adding metrics, logging system, e.t.c. 

In the current implementation, since the `SignerWithProvider` only takes `JsonRpcProvider` as a member, there is no way to add customized logic to the underlying provider. 

We would suggest to add the interface back to allow more flexible operations around the provider.

**Comment by Jordan-Mysten** [comment]
You should still be able to extend the `JsonRpcProvider` class to accomplish this, or pass a custom request client (we don't really have docs, but we should). I don't think we'll re-introduce the provider because I it led to some weird patterns, and was un-necessary overhead. The `SignerWithProvider` class in general is a bit awkward, and I think we'll make some changes to it at some point.
